import { DatePipe } from '@angular/common';
import { Component, DestroyRef, OnInit, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AdminSupportPage, SupportAssignment, SupportCategory, SupportPriority, SupportStatus } from '../../core/models/support.model';
import { SupportService } from '../../core/services/support.service';

@Component({selector:'app-admin-support-list',standalone:true,imports:[FormsModule,RouterLink,DatePipe],template:`
<section class="page"><header><p>Customer operations</p><h1>Support inbox</h1><span>Coordinate help requests and hand specialized work to its owning workflow.</span></header><form class="filters" (ngSubmit)="load(0)"><label>Search<input name="q" [(ngModel)]="q" placeholder="Ticket, subject, or requester"></label><label>Status<select name="status" [(ngModel)]="status"><option value="">All</option><option value="OPEN">Open</option><option value="ASSIGNED">Assigned</option><option value="UNDER_REVIEW">Under review</option><option value="WAITING_FOR_USER">Waiting for user</option><option value="RESOLVED">Resolved</option></select></label><label>Assignment<select name="assignment" [(ngModel)]="assignment"><option value="ALL">All</option><option value="UNASSIGNED">Unassigned</option><option value="ASSIGNED_TO_ME">Assigned to me</option><option value="ASSIGNED">Assigned</option></select></label><label>Category<select name="category" [(ngModel)]="category"><option value="">All</option>@for(c of categories;track c){<option [value]="c">{{label(c)}}</option>}</select></label><label>Priority<select name="priority" [(ngModel)]="priority"><option value="">All</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label><button>Search tickets</button></form>
@if(error()){<p class="state error" role="alert">{{error()}}</p>}@else if(!page()){<p class="state">Loading support tickets…</p>}@else if(page();as p){<p>{{p.totalElements}} support tickets</p><div class="table"><div class="row head"><span>Ticket</span><span>Requester</span><span>Category / subject</span><span>Priority</span><span>Status</span><span>Assignment</span><span>Updated</span></div>@for(t of p.items;track t.ticketId){<a class="row" [routerLink]="['/admin/support',t.ticketId]"><strong>{{short(t.ticketId)}}</strong><span>{{t.safeRequesterLabel}}<small>{{short(t.requesterUserId)}}</small></span><span>{{label(t.category)}}<small>{{t.subject}}</small></span><span class="priority" [class.urgent]="t.priority==='URGENT'">{{label(t.priority)}}</span><span>{{label(t.status)}}</span><span>{{t.assignedAdminId?short(t.assignedAdminId):'Unassigned'}}</span><span>{{t.updatedAt|date:'short'}}</span></a>}</div><nav><button [disabled]="p.page===0" (click)="load(p.page-1)">Previous</button><span>Page {{p.page+1}} of {{p.totalPages||1}}</span><button [disabled]="p.page+1>=p.totalPages" (click)="load(p.page+1)">Next</button></nav>}</section>`,styles:[`
.page{display:grid;gap:1rem}.page header p{color:var(--color-info);font-weight:800;text-transform:uppercase}.filters{display:grid;grid-template-columns:2fr repeat(4,1fr) auto;gap:.7rem;padding:1rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}label{display:grid;gap:.3rem;font-weight:700}input,select,button{padding:.6rem;border:1px solid var(--color-border);background:var(--color-bg-primary);color:var(--color-text-primary)}button{font-weight:800}.table{overflow:auto;border:1px solid var(--color-border)}.row{min-width:1050px;display:grid;grid-template-columns:.8fr 1.1fr 1.8fr .7fr .9fr .9fr .9fr;gap:.7rem;padding:.75rem;border-bottom:1px solid var(--color-border);color:var(--color-text-primary);text-decoration:none}.row:hover{background:rgba(56,189,248,.08)}.head{font-weight:800;background:var(--color-bg-secondary)}.row span{display:grid}.row small{color:var(--color-text-muted)}.priority.urgent{color:#ff8b8b;font-weight:850}nav{display:flex;justify-content:flex-end;gap:1rem;align-items:center}.state{padding:1rem;border:1px solid var(--color-border)}.error{color:var(--color-danger)}@media(max-width:950px){.filters{grid-template-columns:1fr 1fr}}@media(max-width:600px){.filters{grid-template-columns:1fr}}
`]})
export class AdminSupportListComponent implements OnInit{private readonly service=inject(SupportService);private readonly route=inject(ActivatedRoute);private readonly destroy=inject(DestroyRef);readonly page=signal<AdminSupportPage|null>(null);readonly error=signal('');readonly categories:SupportCategory[]=['ACCOUNT_HELP','ORDER_HELP','PAYMENT_HELP','REFUND_HELP','SELLER_HELP','BUSINESS_VERIFICATION','LISTING_HELP','TECHNICAL_ISSUE','OTHER'];readonly routeStatuses:SupportStatus[]=['OPEN','ASSIGNED','UNDER_REVIEW','WAITING_FOR_USER','RESOLVED'];readonly routeAssignments:SupportAssignment[]=['UNASSIGNED','ASSIGNED_TO_ME','ASSIGNED','ALL'];q='';status:SupportStatus|''='';assignment:SupportAssignment='ALL';category:SupportCategory|''='';priority:SupportPriority|''='';ngOnInit(){this.route.queryParamMap.pipe(takeUntilDestroyed(this.destroy)).subscribe(params=>{const status=params.get('status');const assignment=params.get('assignment');this.status=this.routeStatuses.includes(status as SupportStatus)?status as SupportStatus:'';this.assignment=this.routeAssignments.includes(assignment as SupportAssignment)?assignment as SupportAssignment:'ALL';this.load(0);});}load(page:number){this.error.set('');this.service.search({q:this.q,status:this.status,assignment:this.assignment,category:this.category,priority:this.priority,page,size:25,sort:'updatedAt,desc'}).subscribe({next:v=>this.page.set(v),error:e=>this.error.set(e?.error?.error?.message||'Support tickets could not be loaded.')});}short(v:string){return v.length>10?v.slice(0,8)+'…':v;}label(v:string){return v.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}}
