import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { CatalogCategory, CatalogOverview, CategoryStatus, SellerEligibility } from '../../core/models/catalog.model';
import { CatalogService } from '../../core/services/catalog.service';
import { AdminService } from '../../core/services/admin.service';
import { ADMIN_PERMISSIONS } from '../../core/security/admin-permissions';

@Component({
  selector:'app-admin-catalog',standalone:true,imports:[FormsModule,RouterLink],
  template:`
  <section class="catalog-page">
    <header class="hero"><div><p class="eyebrow">Marketplace governance</p><h1>Catalog control room</h1><p>Manage the category hierarchy and seller-facing requirements without rewriting existing marketplace history.</p></div>
      @if(canCreate()){<button class="primary" (click)="showCreate.set(!showCreate())">{{showCreate()?'Close':'New category'}}</button>}
    </header>
    @if(error()){<p class="alert" role="alert">{{error()}}</p>}
    @if(overview();as data){
      <div class="metrics" aria-label="Catalog summary">
        <article><span>Active categories</span><strong>{{data.activeCategories}}</strong></article>
        <article><span>Governed attributes</span><strong>{{data.activeAttributes}}</strong></article>
        <article><span>Seller guidance</span><strong>{{data.activeGuidance}}</strong></article>
        <article class="attention"><span>Not accepting new use</span><strong>{{data.disabledCategories+data.deprecatedCategories}}</strong></article>
      </div>
      @if(showCreate()){
        <form class="create-card" (ngSubmit)="create()"><div><p class="eyebrow">Controlled change</p><h2>Create category</h2><p>Slug and initial rule version are generated by Product Service.</p></div>
          <label>Name<input name="name" [(ngModel)]="createName" maxlength="160" required></label>
          <label>Parent<select name="parent" [(ngModel)]="createParent"><option value="">Root category</option>@for(c of data.categories;track c.id){<option [value]="c.id">{{c.name}}</option>}</select></label>
          <label>Description<textarea name="description" [(ngModel)]="createDescription" maxlength="1000"></textarea></label>
          <label>Seller eligibility<select name="eligibility" [(ngModel)]="createEligibility"><option>BOTH</option><option>INDIVIDUAL</option><option>BUSINESS</option><option>NONE</option></select></label>
          <label>Initial status<select name="createStatus" [(ngModel)]="createStatus"><option>ACTIVE</option><option>DISABLED</option><option>DEPRECATED</option></select></label>
          <label>Display order<input name="order" type="number" min="0" [(ngModel)]="createOrder"></label>
          <button class="primary" [disabled]="saving()">{{saving()?'Creating…':'Create governed category'}}</button>
        </form>
      }
      <form class="filters" (ngSubmit)="load()"><label>Search<input name="q" [(ngModel)]="q" placeholder="Name or slug"></label>
        <label>Status<select name="status" [(ngModel)]="status"><option value="">All states</option><option>ACTIVE</option><option>DISABLED</option><option>DEPRECATED</option></select></label>
        <label>Seller eligibility<select name="eligibility" [(ngModel)]="eligibility"><option value="">All sellers</option><option>BOTH</option><option>INDIVIDUAL</option><option>BUSINESS</option><option>NONE</option></select></label>
        <button>Apply filters</button></form>
      <div class="workbench"><aside><p class="eyebrow">Hierarchy</p><h2>{{data.categories.length}} categories</h2><p>Select a category to inspect its rules, impact, guidance, and complete change history.</p><div class="legend"><span><i class="active"></i>Active</span><span><i class="disabled"></i>Disabled</span><span><i class="deprecated"></i>Deprecated</span></div></aside>
        <div class="table-wrap"><table><thead><tr><th>Category</th><th>Eligibility</th><th>Rules</th><th>Marketplace impact</th><th></th></tr></thead><tbody>
          @for(c of data.categories;track c.id){<tr><td><span class="category-name" [style.padding-left.rem]="depth(c,data.categories)*1.2"><i [class]="c.status.toLowerCase()"></i><span><strong>{{c.name}}</strong><small>{{c.slug}} · v{{c.ruleVersion}}</small></span></span></td><td>{{label(c.sellerEligibility)}}</td><td><span class="policy" [class.off]="!c.listingCreationAllowed">Create {{c.listingCreationAllowed?'on':'off'}}</span><span class="policy" [class.off]="!c.listingSubmissionAllowed">Submit {{c.listingSubmissionAllowed?'on':'off'}}</span></td><td><b>{{c.counts.activeListings}}</b> active · <b>{{c.counts.draftListings}}</b> drafts · <b>{{c.counts.pendingListings}}</b> pending</td><td><a [routerLink]="['/admin/catalog/categories',c.id]">Open →</a></td></tr>}
          @if(!data.categories.length){<tr><td colspan="5" class="empty">No categories match these filters.</td></tr>}
        </tbody></table></div>
      </div>
    }@else if(!error()){<p class="loading">Loading catalog configuration…</p>}
  </section>`,
  styles:[`
  :host{display:block}.catalog-page{display:grid;gap:1.25rem;color:var(--color-text-primary)}.hero{display:flex;align-items:end;justify-content:space-between;gap:2rem;padding:1.5rem;border:1px solid var(--color-border);border-radius:18px;background:linear-gradient(135deg,var(--color-bg-secondary),color-mix(in srgb,var(--color-accent) 10%,var(--color-bg-secondary)))}h1{font-size:clamp(2rem,4vw,3.5rem);line-height:.95;margin:.25rem 0 .75rem;letter-spacing:-.045em}.hero p{max-width:720px;color:var(--color-text-secondary)}.eyebrow{text-transform:uppercase;letter-spacing:.16em;font-size:.72rem;font-weight:800;color:var(--color-accent)}button,.primary{border:1px solid var(--color-border);border-radius:9px;padding:.7rem 1rem;background:var(--color-bg-tertiary);color:inherit;font-weight:700;cursor:pointer}.primary{background:var(--color-accent);color:#07110d;border-color:transparent}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem}.metrics article{padding:1rem;border:1px solid var(--color-border);border-radius:14px;background:var(--color-bg-secondary);display:flex;flex-direction:column;gap:.5rem}.metrics span{color:var(--color-text-secondary);font-size:.8rem}.metrics strong{font-size:1.8rem}.metrics .attention{border-color:#c38a3c}.filters,.create-card{display:grid;gap:.75rem;padding:1rem;border:1px solid var(--color-border);border-radius:14px;background:var(--color-bg-secondary)}.filters{grid-template-columns:2fr 1fr 1fr auto;align-items:end}.create-card{grid-template-columns:1.4fr 1fr 1fr;align-items:end;border-left:4px solid var(--color-accent)}label{display:grid;gap:.35rem;font-size:.78rem;color:var(--color-text-secondary)}input,select,textarea{width:100%;box-sizing:border-box;border:1px solid var(--color-border);border-radius:8px;padding:.65rem;background:var(--color-bg-primary);color:var(--color-text-primary)}textarea{min-height:72px}.workbench{display:grid;grid-template-columns:220px 1fr;border:1px solid var(--color-border);border-radius:16px;overflow:hidden;background:var(--color-bg-secondary)}.workbench aside{padding:1rem;border-right:1px solid var(--color-border)}.workbench aside p:not(.eyebrow){color:var(--color-text-secondary);font-size:.85rem;line-height:1.5}.legend{display:grid;gap:.45rem;margin-top:1.25rem;font-size:.75rem}.legend span,.category-name{display:flex;align-items:center;gap:.6rem}.legend i,.category-name>i{width:8px;height:8px;border-radius:50%;background:#71c58d}.legend i.disabled,.category-name>i.disabled{background:#c38a3c}.legend i.deprecated,.category-name>i.deprecated{background:#858b99}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;min-width:850px}th,td{text-align:left;padding:.85rem;border-bottom:1px solid var(--color-border);font-size:.8rem}th{color:var(--color-text-secondary);font-size:.7rem;text-transform:uppercase;letter-spacing:.08em}.category-name strong,.category-name small{display:block}.category-name small{color:var(--color-text-secondary);margin-top:.2rem}.policy{display:inline-block;padding:.25rem .4rem;margin:.12rem;border-radius:5px;background:color-mix(in srgb,#71c58d 18%,transparent);font-size:.7rem}.policy.off{background:color-mix(in srgb,#c38a3c 18%,transparent)}a{color:var(--color-accent);font-weight:700}.alert{padding:1rem;border:1px solid #b94a57;border-radius:10px;background:color-mix(in srgb,#b94a57 12%,transparent)}.empty,.loading{text-align:center;padding:2rem;color:var(--color-text-secondary)}@media(max-width:900px){.metrics{grid-template-columns:1fr 1fr}.filters,.create-card{grid-template-columns:1fr}.workbench{grid-template-columns:1fr}.workbench aside{border-right:0;border-bottom:1px solid var(--color-border)}}
  `]
})
export class AdminCatalogComponent implements OnInit{
  private readonly service=inject(CatalogService);private readonly admin=inject(AdminService);private readonly router=inject(Router);
  readonly overview=signal<CatalogOverview|null>(null);readonly error=signal('');readonly saving=signal(false);readonly showCreate=signal(false);
  q='';status:CategoryStatus|''='';eligibility:SellerEligibility|''='';createName='';createParent='';createDescription='';createEligibility:SellerEligibility='BOTH';createStatus:CategoryStatus='ACTIVE';createOrder=0;
  ngOnInit(){this.load();}canCreate(){return this.admin.hasPermission(ADMIN_PERMISSIONS.CATALOG_CATEGORY_MANAGE);}
  load(){this.error.set('');this.service.overview({q:this.q,status:this.status,sellerEligibility:this.eligibility}).subscribe({next:v=>this.overview.set(v),error:e=>this.error.set(e?.error?.error?.message||'Catalog configuration could not be loaded.')});}
  create(){if(!this.createName.trim())return;this.saving.set(true);this.service.create({name:this.createName.trim(),parentId:this.createParent||null,description:this.createDescription.trim()||null,displayOrder:this.createOrder,sellerEligibility:this.createEligibility,status:this.createStatus}).subscribe({next:v=>{this.saving.set(false);this.router.navigate(['/admin/catalog/categories',v.category.id]);},error:e=>{this.saving.set(false);this.error.set(e?.error?.error?.message||'Category could not be created.');}});}
  depth(category:CatalogCategory,all:CatalogCategory[]){let depth=0,parent=category.parentId;while(parent&&depth<3){depth++;parent=all.find(v=>v.id===parent)?.parentId||null;}return depth;}
  label(v:string){return v.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
}
