import { DatePipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink, RouterLinkActive } from '@angular/router';
import { finalize, forkJoin, Observable } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { AdminService } from '../../core/services/admin.service';
import { SystemOperationsService } from '../../core/services/system-operations.service';
import { FeatureState, InventoryIssue, JobSummary, MaintenancePreview, MaintenanceResult, OutboxSummary, PageResponse, ReconciliationIssue, SearchStatus, ServiceHealth, SystemSummary } from '../../core/models/system-operations.model';
import { systemOperationsCapability } from './system-operations-capability';

type Section='summary'|'health'|'jobs'|'outbox'|'reconciliation'|'inventory'|'search'|'features';
type ActionKind='job'|'outbox'|'search';

@Component({
 selector:'app-admin-system',standalone:true,imports:[DatePipe,FormsModule,RouterLink,RouterLinkActive],
 template:`
 <section class="ops-page">
  <header class="ops-heading">
   <div><p class="eyebrow">Marketplace runtime</p><h2>System operations</h2><p>Inspect operational evidence and request bounded recovery through the service that owns the work.</p></div>
   <div class="mode" [class.actionable]="!capability().isReadOnly"><span></span>{{capability().isReadOnly?'Read-only access':'Recovery access'}}</div>
  </header>
  <nav class="section-nav" aria-label="System operations sections">
   @for(item of sections;track item.path){<a [routerLink]="item.path" routerLinkActive="active" [routerLinkActiveOptions]="{exact:item.section==='summary'}">{{item.label}}</a>}
  </nav>
  @if(capability().readOnlyReason){<p class="read-only">{{capability().readOnlyReason}}</p>}
  @if(error()){<div class="notice error" role="alert"><strong>Operations data unavailable</strong><span>{{error()}}</span><button type="button" (click)="load()">Try again</button></div>}
  @if(loading()){<div class="loading" aria-live="polite"><span></span>Reading bounded operational signals…</div>}

  @if(!loading()&&section==='summary'&&summary();as value){
   <section class="signal-board" aria-labelledby="runtime-signal-heading">
    <div class="board-copy"><p>Current signal</p><h3 id="runtime-signal-heading">{{value.serviceHealth.secondary===0?'All queried services responded':'Runtime attention required'}}</h3><span>HTTP health and domain correctness are shown separately.</span></div>
    <div class="service-rail" aria-label="Service health rail">
     @for(service of health();track service.serviceKey){<div class="service-node" [attr.data-status]="service.status"><span></span><strong>{{service.displayName}}</strong><small>{{service.status}}</small></div>}
    </div>
   </section>
   <div class="summary-grid">
    <a routerLink="/admin/system/health"><span>Service health</span><strong>{{value.serviceHealth.primary}} healthy</strong><small>{{value.serviceHealth.secondary}} need attention</small></a>
    <a routerLink="/admin/system/jobs"><span>Durable work</span><strong>{{value.jobs.primary}} failed</strong><small>{{value.jobs.secondary}} retryable</small></a>
    <a routerLink="/admin/system/outbox"><span>Outbox delivery</span><strong>{{value.outbox.primary}} failed</strong><small>{{value.outbox.secondary}} terminal</small></a>
    <a routerLink="/admin/system/reconciliation"><span>Reconciliation</span><strong>{{value.reconciliationRequiresAttention}}</strong><small>require operator review</small></a>
    <a routerLink="/admin/system/inventory"><span>Inventory</span><strong>{{value.inventoryPotentiallyStuck}}</strong><small>suspected stale reservations</small></a>
    <a routerLink="/admin/system/search"><span>Search indexing</span><strong>{{value.failedIndexOperations}}</strong><small>failed operations</small></a>
    <a routerLink="/admin/system/features"><span>Runtime features</span><strong>{{value.featureWarnings}}</strong><small>disabled or unavailable</small></a>
   </div>
   @if(value.sourceWarnings.length){<div class="notice warning"><strong>Partial operational view</strong><span>{{value.sourceWarnings.join(' ')}}</span></div>}
   <section class="evidence"><div class="section-title"><div><p class="eyebrow">Audit evidence</p><h3>Recent recovery requests</h3></div><span>Requested does not mean completed</span></div>
    @if(value.recentOperations.length){<div class="table-shell"><table><thead><tr><th>Requested</th><th>Operation</th><th>Target</th><th>Outcome</th><th>Reason</th></tr></thead><tbody>@for(event of value.recentOperations;track event.commandId){<tr><td>{{event.createdAt|date:'medium'}}</td><td>{{label(event.eventType)}}</td><td><code>{{event.targetId}}</code></td><td><span class="status" [attr.data-status]="event.outcome">{{event.outcome}}</span></td><td>{{event.reason}}</td></tr>}</tbody></table></div>}@else{<p class="empty">No administrator recovery requests have been recorded.</p>}
   </section>
  }

  @if(!loading()&&section==='health'){
   <section class="evidence"><div class="section-title"><div><p class="eyebrow">Bounded checks</p><h3>Service health</h3></div><button type="button" (click)="load()">Refresh checks</button></div>
    <p class="context">A healthy HTTP endpoint does not prove payments, search, inventory, or asynchronous work are reconciled.</p>
    <div class="table-shell"><table><thead><tr><th>Service</th><th>Status</th><th>Checked</th><th>Latency</th><th>Safe summary</th></tr></thead><tbody>@for(item of health();track item.serviceKey){<tr><td><strong>{{item.displayName}}</strong></td><td><span class="status" [attr.data-status]="item.status">{{item.status}}</span></td><td>{{item.checkedAt|date:'medium'}}</td><td>{{item.responseLatencyMs===null?'—':item.responseLatencyMs+' ms'}}</td><td>{{item.safeSummary}}</td></tr>}</tbody></table></div>
   </section>
  }

  @if(!loading()&&section==='jobs'){
   <section class="evidence"><div class="section-title"><div><p class="eyebrow">Persistent worker state</p><h3>Failed and pending jobs</h3></div><button type="button" (click)="load()">Refresh</button></div>
    <form class="filters" (ngSubmit)="load()"><label>Service<input name="jobService" [(ngModel)]="serviceFilter" placeholder="PRODUCT"></label><label>Status<select name="jobStatus" [(ngModel)]="statusFilter"><option value="">All</option><option value="FAILURE">Failure states (failed, dead-letter, terminal)</option><option>FAILED</option><option>PENDING</option><option>DEAD_LETTER</option><option>TERMINAL</option><option>SUCCEEDED</option></select></label><button>Apply filters</button></form>
    @if(jobs().length){<div class="table-shell"><table><thead><tr><th>Job</th><th>Owner</th><th>Status</th><th>Attempts</th><th>Next attempt</th><th>Failure</th><th></th></tr></thead><tbody>@for(item of jobs();track item.jobId){<tr><td><strong>{{label(item.jobType)}}</strong><code>{{item.jobId}}</code></td><td>{{item.ownerService}}</td><td><span class="status" [attr.data-status]="item.status">{{item.status}}</span></td><td>{{item.attemptCount}}{{item.maxAttempts===null?'':' / '+item.maxAttempts}}</td><td>{{item.nextAttemptAt?(item.nextAttemptAt|date:'medium'):'—'}}</td><td>{{item.safeFailureSummary||'No failure recorded.'}}</td><td>@if(item.retryable&&capability().canRetry){<button type="button" class="action" (click)="openAction('job',item.jobId)">Review retry</button>}@else{<span class="quiet">Read only</span>}</td></tr>}</tbody></table></div>}@else{<p class="empty">No durable jobs match these filters.</p>}
   </section>
  }

  @if(!loading()&&section==='outbox'){
   <section class="evidence"><div class="section-title"><div><p class="eyebrow">Payload-redacted view</p><h3>Outbox delivery</h3></div><button type="button" (click)="load()">Refresh</button></div>
    <form class="filters" (ngSubmit)="load()"><label>Service<input name="outboxService" [(ngModel)]="serviceFilter" placeholder="PAYMENT"></label><label>Status<select name="outboxStatus" [(ngModel)]="statusFilter"><option value="">All</option><option value="FAILURE">Failure states (failed or dead-letter)</option><option>FAILED</option><option>PENDING</option><option>DEAD_LETTER</option><option>SENT</option></select></label><button>Apply filters</button></form>
    @if(outbox().length){<div class="table-shell"><table><thead><tr><th>Event</th><th>Owner</th><th>Status</th><th>Aggregate</th><th>Attempts</th><th>Failure</th><th></th></tr></thead><tbody>@for(item of outbox();track item.eventId){<tr><td><strong>{{item.eventType}}</strong><code>{{item.eventId}}</code></td><td>{{item.ownerService}}</td><td><span class="status" [attr.data-status]="item.status">{{item.status}}</span></td><td>{{item.aggregateType}}<code>{{item.aggregateId}}</code></td><td>{{item.attemptCount}}</td><td>{{item.safeFailureSummary||'No failure recorded.'}}</td><td>@if(item.retryable&&capability().canRetry){<button type="button" class="action" (click)="openAction('outbox',item.eventId)">Review retry</button>}@else{<span class="quiet">Read only</span>}</td></tr>}</tbody></table></div>}@else{<p class="empty">No outbox events match these filters.</p>}
   </section>
  }

  @if(!loading()&&section==='reconciliation'){
   <section class="evidence"><div class="section-title"><div><p class="eyebrow">Domain correctness</p><h3>Financial reconciliation</h3></div><button type="button" (click)="load()">Refresh</button></div><div class="notice warning"><strong>Review only</strong><span>Payment does not currently expose a safe provider recheck command. ADM-SYS does not add one or edit refund status.</span></div>
    @if(reconciliation().length){<div class="table-shell"><table><thead><tr><th>Issue</th><th>Target</th><th>Local state</th><th>External state</th><th>Last checked</th><th>Summary</th></tr></thead><tbody>@for(item of reconciliation();track item.issueId){<tr><td><strong>{{label(item.issueType)}}</strong><code>{{item.issueId}}</code></td><td><a [routerLink]="item.targetType==='REFUND'?['/admin/refunds',item.targetId]:['/admin/payments',item.targetId]">{{item.targetType}} {{item.targetId}}</a></td><td>{{item.localState}}</td><td>{{item.externalStateSafe||'Unconfirmed'}}</td><td>{{item.lastCheckedAt?(item.lastCheckedAt|date:'medium'):'—'}}</td><td>{{item.safeSummary}}</td></tr>}</tbody></table></div>}@else{<p class="empty">No payment or refund reconciliation issues require attention.</p>}
   </section>
  }

  @if(!loading()&&section==='inventory'){
   <section class="evidence"><div class="section-title"><div><p class="eyebrow">Reservation lifecycle</p><h3>Inventory anomalies</h3></div><button type="button" (click)="load()">Refresh</button></div><p class="context">Only suspected anomalies are shown. Quantity and reservation state cannot be edited here.</p>
    @if(inventory().length){<div class="table-shell"><table><thead><tr><th>Reservation</th><th>Issue</th><th>Listing</th><th>Quantity</th><th>Expired</th><th>Summary</th></tr></thead><tbody>@for(item of inventory();track item.reservationId){<tr><td><code>{{item.reservationId}}</code></td><td><span class="status" data-status="FAILED">{{label(item.issueType)}}</span></td><td><code>{{item.listingId||'—'}}</code></td><td>{{item.quantity}}</td><td>{{item.expiresAt|date:'medium'}}</td><td>{{item.safeSummary}}</td></tr>}</tbody></table></div>}@else{<p class="empty">No expired active reservations were detected.</p>}
   </section>
  }

  @if(!loading()&&section==='search'){
   <section class="evidence"><div class="section-title"><div><p class="eyebrow">Derived projection</p><h3>Search indexing</h3></div><button type="button" (click)="load()">Refresh</button></div>
    <div class="search-layout"><div>@for(item of search();track item.ownerService){<article class="search-state"><div><span class="status" [attr.data-status]="item.status">{{item.status}}</span><small>{{item.indexVersion}}</small></div><h4>{{item.pendingOperations}} pending · {{item.failedOperations}} failed</h4><p>{{item.safeSummary}}</p><span>Last successful apply: {{item.lastSuccessfulIndexingAt?(item.lastSuccessfulIndexingAt|date:'medium'):'No recorded apply'}}</span></article>}</div>
     <form class="reindex-box" (ngSubmit)="reviewListingReindex()"><p class="eyebrow">Bounded command</p><h4>Reindex one listing</h4><p>Product will reread current authoritative state and queue one UPSERT or DELETE. Listing state does not change.</p><label>Listing ID<input name="listingId" [(ngModel)]="listingId" maxlength="26" required></label><button class="action" [disabled]="!capability().canMaintainSearch">Review reindex</button></form></div>
    @for(status of search();track status.ownerService){@if(status.issues.length){<div class="table-shell"><table><thead><tr><th>Work</th><th>Listing</th><th>Status</th><th>Attempts</th><th>Failure</th><th></th></tr></thead><tbody>@for(item of status.issues;track item.workId){<tr><td><code>{{item.workId}}</code></td><td><code>{{item.targetId}}</code></td><td><span class="status" [attr.data-status]="item.status">{{item.status}}</span></td><td>{{item.attemptCount}}</td><td>{{item.safeFailureSummary||'No failure recorded.'}}</td><td>@if(item.retryable&&capability().canRetry){<button class="action" type="button" (click)="openAction('job',item.workId)">Review retry</button>}</td></tr>}</tbody></table></div>}}
    <div class="notice"><strong>Legacy Search Maintenance remains gated</strong><span>Full rebuild, embedding backfill, vector promotion, and recovery stay on the independent experimental route. ADM-SYS integrates only bounded production search work.</span></div>
   </section>
  }

  @if(!loading()&&section==='features'){
   <section class="evidence"><div class="section-title"><div><p class="eyebrow">Curated configuration</p><h3>Feature and maintenance status</h3></div><button type="button" (click)="load()">Refresh</button></div><div class="notice"><strong>Read-only configuration</strong><span>These flags are environment or service-configuration backed. No second runtime flag database was created.</span></div>
    <div class="feature-list">@for(item of features();track item.ownerService+'-'+item.featureKey){<article><div><span class="status" [attr.data-status]="item.status">{{item.status}}</span><small>{{item.ownerService}}</small></div><h4>{{item.displayName}}</h4><p>{{item.safeSummary}}</p><span>{{item.source}}</span></article>}</div>
   </section>
  }

  @if(actionTarget();as target){<div class="modal-backdrop" (click)="closeAction()"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="recovery-heading" (click)="$event.stopPropagation()"><p class="eyebrow">Safe command preview</p><h3 id="recovery-heading">{{preview()?'Confirm recovery request':'Explain this recovery request'}}</h3>
   @if(!preview()){<p>The reason, actor, target, correlation ID, and result will be audited.</p><label>Operational reason<textarea [(ngModel)]="actionReason" rows="4" maxlength="1000" placeholder="Explain why this bounded retry is needed."></textarea></label><div class="modal-actions"><button class="action" type="button" [disabled]="actionReason.trim().length<10||actionBusy()" (click)="loadPreview()">Run safe preview</button><button type="button" (click)="closeAction()">Cancel</button></div>}
   @else if(preview();as impact){<dl class="impact"><div><dt>Owner</dt><dd>{{impact.ownerService}}</dd></div><div><dt>Current state</dt><dd>{{impact.currentState}}</dd></div><div><dt>Operation</dt><dd>{{impact.expectedOperation}}</dd></div><div><dt>Customer impact</dt><dd>{{impact.customerImpact}}</dd></div></dl>@if(impact.warnings.length){<ul>@for(warning of impact.warnings;track warning){<li>{{warning}}</li>}</ul>}@if(!impact.allowed){<p class="notice error">{{impact.denialReason||'This target is not retryable.'}}</p>}<div class="modal-actions"><button class="action" type="button" [disabled]="!impact.allowed||actionBusy()" (click)="confirmAction()">Request {{target.kind==='search'?'reindex':'retry'}}</button><button type="button" (click)="closeAction()">Cancel</button></div>}
   @if(actionError()){<p class="notice error" role="alert">{{actionError()}}</p>}
  </section></div>}
  @if(lastResult();as result){<div class="result-toast" role="status"><strong>{{result.result}}</strong><span>{{result.safeSummary}}</span><button type="button" (click)="lastResult.set(null)">Dismiss</button></div>}
 </section>`,
 styles:[`
 :host{--ops-ink:#142632;--ops-slate:#516875;--ops-line:#cbd7dc;--ops-paper:#f6f9fa;--ops-green:#267553;--ops-amber:#af6b12;--ops-red:#a43b3f;--ops-cyan:#287c91;display:block;color:var(--ops-ink)}
 .ops-page{display:grid;gap:1.25rem}.ops-heading{display:flex;justify-content:space-between;gap:2rem;align-items:flex-end;padding:1.5rem;border:1px solid var(--ops-line);background:linear-gradient(105deg,#eef5f6 0 62%,#dcebed 62%)}.ops-heading h2{font-family:var(--font-display);font-size:clamp(1.8rem,4vw,3rem);margin:.1rem 0}.ops-heading p{max-width:62ch;margin:.25rem 0;color:var(--ops-slate)}.eyebrow{text-transform:uppercase;letter-spacing:.13em;font-size:.72rem;font-weight:800;color:var(--ops-cyan)!important}.mode{display:flex;align-items:center;gap:.5rem;white-space:nowrap;font-weight:800}.mode span{width:.65rem;height:.65rem;border-radius:50%;background:var(--ops-slate)}.mode.actionable span{background:var(--ops-green);box-shadow:0 0 0 5px #2675531f}.section-nav{display:flex;gap:.25rem;overflow:auto;border-bottom:1px solid var(--ops-line)}.section-nav a{padding:.7rem .85rem;text-decoration:none;color:var(--ops-slate);font-weight:700;border-bottom:3px solid transparent;white-space:nowrap}.section-nav a.active{color:var(--ops-ink);border-color:var(--ops-cyan)}
 .read-only,.context{margin:0;color:var(--ops-slate)}.signal-board{display:grid;grid-template-columns:minmax(220px,.75fr) 2fr;border:1px solid var(--ops-line);background:white}.board-copy{padding:1.4rem;background:var(--ops-ink);color:white}.board-copy p,.board-copy span{margin:0;color:#c9d8dd}.board-copy h3{font-size:1.55rem;margin:.4rem 0}.service-rail{display:grid;grid-template-columns:repeat(4,1fr);align-items:center;padding:1.2rem;gap:1rem}.service-node{display:grid;grid-template-columns:auto 1fr;column-gap:.5rem;align-items:center}.service-node>span{grid-row:1/3;width:.72rem;height:.72rem;border-radius:50%;background:var(--ops-slate)}.service-node[data-status=HEALTHY]>span{background:var(--ops-green)}.service-node[data-status=DEGRADED]>span,.service-node[data-status=UNKNOWN]>span{background:var(--ops-amber)}.service-node[data-status=UNAVAILABLE]>span{background:var(--ops-red)}.service-node small{color:var(--ops-slate);font-size:.68rem}.summary-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem}.summary-grid a{display:flex;min-height:115px;flex-direction:column;padding:1rem;border:1px solid var(--ops-line);background:white;color:inherit;text-decoration:none}.summary-grid a:hover,.summary-grid a:focus-visible{border-color:var(--ops-cyan);transform:translateY(-2px)}.summary-grid span{color:var(--ops-slate);font-size:.8rem}.summary-grid strong{font-size:1.5rem;margin-top:auto}.summary-grid small{color:var(--ops-slate)}
 .evidence{display:grid;gap:1rem}.section-title{display:flex;justify-content:space-between;align-items:end;gap:1rem}.section-title h3{font-size:1.45rem;margin:.15rem 0}.section-title>span{color:var(--ops-slate);font-size:.82rem}.section-title button,.filters button,.modal button,.result-toast button{border:1px solid var(--ops-line);background:white;padding:.55rem .8rem;font-weight:700;color:var(--ops-ink)}.table-shell{overflow:auto;border:1px solid var(--ops-line);background:white}table{width:100%;border-collapse:collapse;min-width:850px}th,td{text-align:left;padding:.75rem;border-bottom:1px solid #e3eaed;vertical-align:top}th{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:var(--ops-slate);background:#f0f5f6}td{font-size:.85rem}td strong,td code{display:block}code{font-size:.73rem;color:var(--ops-slate);margin-top:.2rem;word-break:break-all}.status{display:inline-flex;padding:.2rem .48rem;border-radius:999px;background:#e8eef0;color:var(--ops-slate);font-size:.68rem;font-weight:850;letter-spacing:.04em}.status[data-status=HEALTHY],.status[data-status=SUCCEEDED],.status[data-status=SENT],.status[data-status=ENABLED],.status[data-status=ACCEPTED]{background:#dff1e8;color:var(--ops-green)}.status[data-status=FAILED],.status[data-status=DEAD_LETTER],.status[data-status=UNAVAILABLE],.status[data-status=REJECTED]{background:#f7e2e3;color:var(--ops-red)}.status[data-status=PENDING],.status[data-status=DEGRADED],.status[data-status=UNKNOWN],.status[data-status=DISABLED]{background:#f7eddc;color:var(--ops-amber)}
 .filters{display:flex;align-items:end;gap:.75rem;flex-wrap:wrap}.filters label,.reindex-box label,.modal label{display:grid;gap:.35rem;font-size:.76rem;font-weight:750;color:var(--ops-slate)}input,select,textarea{border:1px solid var(--ops-line);padding:.62rem;background:white;color:var(--ops-ink);font:inherit}.action{border:0!important;background:var(--ops-ink)!important;color:white!important;padding:.58rem .8rem!important;font-weight:800}.action:disabled{opacity:.45}.quiet{font-size:.75rem;color:var(--ops-slate)}.empty{padding:1.25rem;border:1px dashed var(--ops-line);background:var(--ops-paper);color:var(--ops-slate)}.notice{display:flex;gap:.75rem;align-items:flex-start;padding:.85rem 1rem;border-left:4px solid var(--ops-cyan);background:#e8f2f4}.notice span{color:var(--ops-slate)}.notice.warning{border-color:var(--ops-amber);background:#fbf3e7}.notice.error{border-color:var(--ops-red);background:#f9e8e8}.loading{display:flex;align-items:center;gap:.7rem;padding:2rem;color:var(--ops-slate)}.loading span{width:1rem;height:1rem;border:2px solid var(--ops-line);border-top-color:var(--ops-cyan);border-radius:50%;animation:spin .8s linear infinite}
 .search-layout{display:grid;grid-template-columns:1.4fr 1fr;gap:1rem}.search-state,.reindex-box,.feature-list article{border:1px solid var(--ops-line);background:white;padding:1rem}.search-state>div,.feature-list article>div{display:flex;justify-content:space-between}.search-state h4,.reindex-box h4,.feature-list h4{margin:.65rem 0}.search-state p,.reindex-box p,.feature-list p{color:var(--ops-slate)}.feature-list{display:grid;grid-template-columns:repeat(3,1fr);gap:.75rem}.feature-list article>span,.search-state>span{font-size:.72rem;color:var(--ops-slate)}.modal-backdrop{position:fixed;inset:0;background:#10232fcc;display:grid;place-items:center;padding:1rem;z-index:100}.modal{width:min(620px,100%);max-height:90vh;overflow:auto;background:white;border-top:5px solid var(--ops-cyan);padding:1.35rem;box-shadow:0 24px 70px #0005}.modal h3{font-size:1.5rem}.modal textarea{width:100%;resize:vertical}.modal-actions{display:flex;gap:.65rem;justify-content:flex-end;margin-top:1rem}.impact{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}.impact div{padding:.7rem;background:var(--ops-paper)}.impact dt{font-size:.7rem;color:var(--ops-slate);text-transform:uppercase}.impact dd{margin:.25rem 0 0}.result-toast{position:fixed;right:1rem;bottom:1rem;z-index:90;display:grid;grid-template-columns:auto 1fr auto;gap:.75rem;align-items:center;max-width:620px;padding:1rem;background:var(--ops-ink);color:white;box-shadow:0 12px 40px #0004}.result-toast span{color:#d4e0e4}
 @keyframes spin{to{transform:rotate(360deg)}}@media(max-width:1000px){.summary-grid{grid-template-columns:repeat(2,1fr)}.service-rail{grid-template-columns:repeat(2,1fr)}.feature-list{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.ops-heading,.section-title{align-items:flex-start;flex-direction:column}.signal-board,.search-layout{grid-template-columns:1fr}.summary-grid,.feature-list{grid-template-columns:1fr}.impact{grid-template-columns:1fr}.result-toast{left:1rem;grid-template-columns:1fr}.mode{align-self:flex-start}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}.summary-grid a:hover{transform:none}}
 `]
})
export class AdminSystemComponent {
 private readonly api=inject(SystemOperationsService);private readonly admin=inject(AdminService);private readonly route=inject(ActivatedRoute);private readonly destroy=inject(DestroyRef);
 readonly section=(this.route.snapshot.data['systemSection']??'summary') as Section;
 readonly sections=[{label:'Overview',path:'/admin/system',section:'summary'},{label:'Health',path:'/admin/system/health',section:'health'},{label:'Jobs',path:'/admin/system/jobs',section:'jobs'},{label:'Outbox',path:'/admin/system/outbox',section:'outbox'},{label:'Reconciliation',path:'/admin/system/reconciliation',section:'reconciliation'},{label:'Inventory',path:'/admin/system/inventory',section:'inventory'},{label:'Search',path:'/admin/system/search',section:'search'},{label:'Features',path:'/admin/system/features',section:'features'}];
 readonly capability=computed(()=>systemOperationsCapability(this.admin.currentAdmin()?.permissions??[]));readonly loading=signal(false);readonly error=signal<string|null>(null);readonly summary=signal<SystemSummary|null>(null);readonly health=signal<ServiceHealth[]>([]);readonly jobs=signal<JobSummary[]>([]);readonly outbox=signal<OutboxSummary[]>([]);readonly reconciliation=signal<ReconciliationIssue[]>([]);readonly inventory=signal<InventoryIssue[]>([]);readonly search=signal<SearchStatus[]>([]);readonly features=signal<(FeatureState&{ownerService:string})[]>([]);readonly actionTarget=signal<{kind:ActionKind;id:string}|null>(null);readonly preview=signal<MaintenancePreview|null>(null);readonly actionBusy=signal(false);readonly actionError=signal<string|null>(null);readonly lastResult=signal<MaintenanceResult|null>(null);
 serviceFilter='';statusFilter='';listingId='';actionReason='';
 constructor(){
  const detailId=this.route.snapshot.paramMap.get(this.section==='jobs'?'jobId':'eventId');
  if((this.section!=='jobs'&&this.section!=='outbox')||detailId){this.load();return;}
  this.route.queryParamMap.pipe(takeUntilDestroyed(this.destroy)).subscribe(params=>{
   const status=params.get('status');
   const allowed=this.section==='jobs'?['FAILURE','FAILED','PENDING','DEAD_LETTER','TERMINAL','SUCCEEDED']:['FAILURE','FAILED','PENDING','DEAD_LETTER','SENT'];
   this.statusFilter=status&&allowed.includes(status)?status:'';this.load();
  });
 }
 load(){this.loading.set(true);this.error.set(null);let request:Observable<unknown>;switch(this.section){case'summary':request=forkJoin({summary:this.api.summary(),health:this.api.health()});break;case'health':request=this.api.health();break;case'jobs':{const id=this.route.snapshot.paramMap.get('jobId');request=id?this.api.job(id):this.api.jobs({service:this.serviceFilter,status:this.statusFilter});break;}case'outbox':{const id=this.route.snapshot.paramMap.get('eventId');request=id?this.api.outboxEvent(id):this.api.outbox({service:this.serviceFilter,status:this.statusFilter});break;}case'reconciliation':request=this.api.reconciliation();break;case'inventory':request=this.api.inventory();break;case'search':request=this.api.search();break;case'features':request=this.api.features();break;}
  request.pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroy)).subscribe({next:value=>this.accept(value),error:error=>this.error.set(this.message(error))});}
 private accept(value:unknown){switch(this.section){case'summary':{const data=value as {summary:SystemSummary;health:ServiceHealth[]};this.summary.set(data.summary);this.health.set(data.health);break;}case'health':this.health.set(value as ServiceHealth[]);break;case'jobs':this.jobs.set('items'in(value as object)?(value as PageResponse<JobSummary>).items:[value as JobSummary]);break;case'outbox':this.outbox.set('items'in(value as object)?(value as PageResponse<OutboxSummary>).items:[value as OutboxSummary]);break;case'reconciliation':this.reconciliation.set((value as PageResponse<ReconciliationIssue>).items);break;case'inventory':this.inventory.set((value as PageResponse<InventoryIssue>).items);break;case'search':this.search.set(value as SearchStatus[]);break;case'features':{const raw=value as FeatureState[];this.features.set(raw.map(item=>({...item,ownerService:this.ownerFromSource(item.source)})));break;}}}
 openAction(kind:ActionKind,id:string){this.actionTarget.set({kind,id});this.preview.set(null);this.actionReason='';this.actionError.set(null);}reviewListingReindex(){if(this.listingId.trim())this.openAction('search',this.listingId.trim());}
 closeAction(){if(!this.actionBusy()){this.actionTarget.set(null);this.preview.set(null);this.actionError.set(null);}}
 loadPreview(){const target=this.actionTarget();if(!target)return;this.actionBusy.set(true);this.actionError.set(null);const request:Observable<MaintenancePreview>=target.kind==='job'?this.api.previewJob(target.id,this.actionReason):target.kind==='outbox'?this.api.previewOutbox(target.id,this.actionReason):this.api.previewReindex(target.id,this.actionReason);request.pipe(finalize(()=>this.actionBusy.set(false)),takeUntilDestroyed(this.destroy)).subscribe({next:value=>this.preview.set(value),error:error=>this.actionError.set(this.message(error))});}
 confirmAction(){const target=this.actionTarget(),impact=this.preview();if(!target||!impact?.allowed)return;this.actionBusy.set(true);this.actionError.set(null);const key=crypto.randomUUID();const body={reason:this.actionReason};const request:Observable<MaintenanceResult>=target.kind==='job'?this.api.retryJob(target.id,body,key):target.kind==='outbox'?this.api.retryOutbox(target.id,body,key):this.api.reindex(target.id,body,key);request.pipe(finalize(()=>this.actionBusy.set(false)),takeUntilDestroyed(this.destroy)).subscribe({next:value=>{this.lastResult.set(value);this.closeAction();this.load();},error:error=>this.actionError.set(this.message(error))});}
 label(value:string){return value.toLowerCase().split('_').map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(' ');}private ownerFromSource(source:string){const first=source.split(' ')[0]?.toUpperCase();return ['PRODUCT','ORDER','PAYMENT','INVENTORY'].includes(first)?first:'PLATFORM';}
 private message(error:unknown){if(error instanceof HttpErrorResponse){const code=error.error?.error?.code;const message=error.error?.error?.message;return [code,message].filter(Boolean).join(' · ')||`Request failed (${error.status}).`;}return error instanceof Error?error.message:'The operational request failed.';}
}
