import { DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { DisputePage } from '../../core/models/order-dispute.model';
import { OrderDisputeService } from '../../core/services/order-dispute.service';

@Component({selector:'app-admin-dispute-list',standalone:true,imports:[FormsModule,RouterLink,DatePipe],template:`
<section class="page"><header><p>Commerce operations</p><h1>Disputes</h1><span>Investigate transaction issues without moving money or changing enforcement.</span></header>
<form class="filters" (ngSubmit)="load(0)"><label>Search<input name="q" [(ngModel)]="q" placeholder="Dispute or order ID"></label><label>Status<select name="status" [(ngModel)]="status"><option value="">All</option><option value="OPEN">Open</option><option value="UNDER_ADMIN_REVIEW">Under review</option><option value="WAITING_FOR_BUYER">Waiting for buyer</option><option value="WAITING_FOR_SELLER">Waiting for seller</option><option value="READY_FOR_DECISION">Ready for decision</option><option value="REFUND_RECOMMENDED">Refund recommended</option></select></label><label>Assignment<select name="assignment" [(ngModel)]="assignment"><option value="ALL">All</option><option value="UNASSIGNED">Unassigned</option><option value="ASSIGNED_TO_ME">Assigned to me</option><option value="ASSIGNED">Assigned</option></select></label><label>Priority<select name="priority" [(ngModel)]="priority"><option value="">All</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><button>Search disputes</button></form>
@if(error()){<p class="state error">{{error()}}</p>}@else if(!page()){<p class="state">Loading disputes…</p>}@else if(page();as p){<p>{{p.totalElements}} disputes</p><div class="table"><div class="row head"><span>Dispute</span><span>Order / business</span><span>Reason</span><span>Priority</span><span>Status</span><span>Assignment</span><span>Created</span></div>@for(d of p.content;track d.disputeId){<a class="row" [routerLink]="['/admin/disputes',d.disputeId]"><strong>{{short(d.disputeId)}}</strong><span>{{short(d.orderId)}}<small>{{short(d.businessId)}}</small></span><span>{{label(d.reasonCode)}}</span><span>{{label(d.priority)}}</span><span>{{label(d.status)}}</span><span>{{d.assignedAdminId?short(d.assignedAdminId):'Unassigned'}}</span><span>{{d.createdAt|date:'short'}}</span></a>}</div><nav><button [disabled]="p.page===0" (click)="load(p.page-1)">Previous</button><span>Page {{p.page+1}} of {{p.totalPages||1}}</span><button [disabled]="p.page+1>=p.totalPages" (click)="load(p.page+1)">Next</button></nav>}</section>`,styles:[`.page{display:grid;gap:1rem}.page header p{color:var(--color-info);font-weight:800;text-transform:uppercase}.filters{display:grid;grid-template-columns:2fr repeat(3,1fr) auto;gap:.7rem;padding:1rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}label{display:grid;gap:.3rem;font-weight:700}input,select,button{padding:.6rem;border:1px solid var(--color-border);background:var(--color-bg-primary);color:var(--color-text-primary)}button{font-weight:800}.table{overflow:auto;border:1px solid var(--color-border)}.row{min-width:980px;display:grid;grid-template-columns:1fr 1.3fr 1.3fr .7fr 1fr 1fr 1fr;gap:.7rem;padding:.75rem;border-bottom:1px solid var(--color-border);color:var(--color-text-primary);text-decoration:none}.row:hover{background:rgba(56,189,248,.08)}.head{font-weight:800;background:var(--color-bg-secondary)}.row span{display:grid}.row small{color:var(--color-text-muted)}nav{display:flex;justify-content:flex-end;gap:1rem;align-items:center}.state{padding:1rem;border:1px solid var(--color-border)}.error{color:var(--color-danger)}@media(max-width:800px){.filters{grid-template-columns:1fr}}`]} )
export class AdminDisputeListComponent implements OnInit{private readonly service=inject(OrderDisputeService);readonly page=signal<DisputePage|null>(null);readonly error=signal('');q='';status='';assignment='ALL';priority='';ngOnInit(){this.load(0);}load(page:number){this.error.set('');this.service.adminSearch({q:this.q,status:this.status,assignment:this.assignment,priority:this.priority,page,size:25,sort:'priority,desc'}).subscribe({next:v=>this.page.set(v),error:e=>this.error.set(e?.error?.error?.message||'Disputes could not be loaded.')});}short(v:string){return v.slice(0,8)+'…';}label(v:string){return v.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}}
