import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, DestroyRef, OnInit, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AdminPage, AdminPaymentSummary } from '../../core/models/admin-finance.model';
import { AdminFinanceService } from '../../core/services/admin-finance.service';

@Component({selector:'app-admin-payment-list',standalone:true,imports:[FormsModule,RouterLink,CurrencyPipe,DatePipe],template:`
<section class="finance-page"><header><p class="eyebrow">Financial operations</p><h1>Payments</h1><p>Trace captured value, refund exposure, and order context without revealing payment credentials.</p></header>
<form class="filters" (ngSubmit)="load(0)"><label>Payment or provider reference<input name="q" [(ngModel)]="q" placeholder="Exact identifier"></label><label>Status<select name="status" [(ngModel)]="status"><option value="">All statuses</option><option>SUCCEEDED</option><option>PROCESSING</option><option>FAILED</option></select></label><label>Refund status<select name="refundStatus" [(ngModel)]="refundStatus"><option value="">Any refund state</option><option>PENDING</option><option>PROCESSING</option><option>SUCCEEDED</option><option>FAILED</option></select></label><button>Apply filters</button></form>
@if(error()){<p class="state error" role="alert">{{error()}}</p>}@else if(!page()){<p class="state">Loading payment ledger…</p>}@else if(page();as p){<div class="ledger"><div class="row head"><span>Payment</span><span>Order / buyer</span><span>Businesses</span><span>Captured</span><span>Refund position</span><span>Status</span><span>Created</span></div>@for(item of p.content;track item.paymentId){<a class="row" [routerLink]="['/admin/payments',item.paymentId]"><strong>{{short(item.paymentId)}}</strong><span>{{item.orderId?short(item.orderId):'Order unavailable'}}<small>{{item.buyerDisplayName}}</small></span><span>{{item.businessDisplayNames.join(', ')||'Unavailable'}}</span><span>{{item.capturedAmount|currency:item.currency}}</span><span>{{item.refundedAmount|currency:item.currency}} refunded<small>{{item.refundableAmount|currency:item.currency}} available</small></span><span class="status" [attr.data-state]="item.paymentStatus">{{label(item.paymentStatus)}}</span><span>{{item.createdAt|date:'short'}}</span></a>}@empty{<p class="state">No payments match these filters.</p>}</div><nav><button [disabled]="p.page===0" (click)="load(p.page-1)">Previous</button><span>{{p.totalElements}} payments · Page {{p.page+1}} of {{p.totalPages||1}}</span><button [disabled]="p.page+1>=p.totalPages" (click)="load(p.page+1)">Next</button></nav>}</section>`,styles:[`${styles()}`]})
export class AdminPaymentListComponent implements OnInit{private readonly service=inject(AdminFinanceService);private readonly route=inject(ActivatedRoute);private readonly destroy=inject(DestroyRef);readonly page=signal<AdminPage<AdminPaymentSummary>|null>(null);readonly error=signal('');readonly statuses=['SUCCEEDED','PROCESSING','FAILED'];q='';status='';refundStatus='';ngOnInit(){this.route.queryParamMap.pipe(takeUntilDestroyed(this.destroy)).subscribe(params=>{const status=params.get('status');this.status=status&&this.statuses.includes(status)?status:'';this.load(0);});}load(page:number){this.error.set('');this.service.payments({q:this.q,status:this.status,refundStatus:this.refundStatus,page,size:25,sort:'createdAt,desc'}).subscribe({next:v=>this.page.set(v),error:e=>this.error.set(e?.error?.error?.message||'Payments could not be loaded.')});}short(v:string){return v.length>12?v.slice(0,10)+'…':v;}label(v:string){return(v||'').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}}
function styles(){return `.finance-page{display:grid;gap:1.25rem}.eyebrow{margin:0;color:var(--color-info);font:800 .75rem/1.2 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}h1{margin:.15rem 0;font-size:clamp(2rem,4vw,3.2rem)}header>p:last-child{color:var(--color-text-muted);max-width:68ch}.filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:.8rem;padding:1rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}label{display:grid;gap:.35rem;font-weight:750}input,select,button{min-height:2.65rem;padding:.6rem .7rem;border:1px solid var(--color-border);background:var(--color-bg-primary);color:var(--color-text-primary)}button{font-weight:800}.ledger{overflow:auto;border:1px solid var(--color-border)}.row{min-width:1080px;display:grid;grid-template-columns:1fr 1.25fr 1.2fr .85fr 1.15fr .8fr .9fr;gap:.8rem;align-items:center;padding:.8rem;border-bottom:1px solid var(--color-border);color:var(--color-text-primary);text-decoration:none}.row:not(.head):hover{background:rgba(56,189,248,.07)}.head{font:800 .75rem/1.2 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.06em;background:var(--color-bg-secondary)}.row span{display:grid;gap:.18rem}.row small{color:var(--color-text-muted)}.status{font-weight:800}.status[data-state=SUCCEEDED]{color:var(--color-success)}.status[data-state=FAILED]{color:var(--color-danger)}nav{display:flex;justify-content:flex-end;align-items:center;gap:1rem}.state{padding:1rem;border:1px solid var(--color-border)}.error{color:var(--color-danger)}@media(max-width:800px){.filters{grid-template-columns:1fr}nav{justify-content:space-between;flex-wrap:wrap}}`;}
