import { DatePipe, KeyValuePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AdminReportDetail, ReportSeverity } from '../../core/models/report.model';
import { InvestigationCaseSummary } from '../../core/models/investigation-case.model';
import { InvestigationCaseService } from '../../core/services/investigation-case.service';
import { ReportService } from '../../core/services/report.service';
import { ToastService } from '../../core/services/toast.service';
import { reportAdminCapabilities } from './report-admin-capability';
import { isReportEvidenceTimestamp, rawReportEvidenceValue, reportEvidenceLabel } from './report-evidence-presentation';

@Component({
  selector:'app-admin-report-detail',standalone:true,imports:[DatePipe,KeyValuePipe,FormsModule,RouterLink],
  template:`
    <section class="page"><header><div><a routerLink="/admin/reports">← Report inbox</a><p class="eyebrow">Trust & Safety allegation</p><h1>{{ report()?.safeTargetLabel || 'Report detail' }}</h1></div>@if(report();as item){<div class="version"><span class="chip">{{ label(item.status) }}</span><span>v{{ item.version }}</span></div>}</header>
    @if(loading()){<div class="state">Loading report...</div>}@else if(errorMsg()){<div class="state error" role="alert">{{ errorMsg() }} <button (click)="load()">Retry</button></div>}@else if(report();as item){
      <section class="summary"><dl><div><dt>Report</dt><dd><code>{{ item.reportId }}</code></dd></div><div><dt>Reason</dt><dd>{{ label(item.reasonCode) }}</dd></div><div><dt>Severity</dt><dd>{{ item.severity }}</dd></div><div><dt>Reporter</dt><dd>{{ item.reporterSummary.safeDisplayName }}<small>{{ item.reporterSummary.userId }}</small></dd></div><div><dt>Assignment</dt><dd>{{ item.assignedAdmin?.safeDisplayName || 'Unassigned' }}</dd></div><div><dt>Created</dt><dd>{{ item.createdAt|date:'medium' }}</dd></div></dl>@if(item.description){<div class="statement"><span>User-provided context</span><p>{{ item.description }}</p></div>}</section>
      <section class="evidence"><div class="evidence-heading"><div><p class="eyebrow">Evidence seam</p><h2>Reported snapshot</h2></div><span aria-hidden="true">→</span><div><p class="eyebrow">Live lookup</p><h2>Current state</h2></div></div><div class="evidence-grid"><article><p class="timestamp" [attr.title]="rawEvidenceValue(item.targetSnapshot['capturedAt'])">Immutable · {{ timestampValue(item.targetSnapshot['capturedAt']) | date:'medium' }}</p><dl>@for(field of item.targetSnapshot|keyvalue;track field.key){<div><dt>{{ evidenceLabel(field.key) }}</dt><dd [attr.title]="evidenceTimestamp(field.key,field.value) ? rawEvidenceValue(field.value) : null">@if(evidenceTimestamp(field.key,field.value)){ {{ timestampValue(field.value) | date:'medium' }} }@else{ {{ display(field.value) }} }</dd></div>}</dl></article><article class="current"><p class="timestamp">Fetched when this page loaded</p><dl>@for(field of item.currentTargetSummary|keyvalue;track field.key){<div><dt>{{ evidenceLabel(field.key) }}</dt><dd [attr.title]="evidenceTimestamp(field.key,field.value) ? rawEvidenceValue(field.value) : null">@if(evidenceTimestamp(field.key,field.value)){ {{ timestampValue(field.value) | date:'medium' }} }@else{ {{ display(field.value) }} }</dd></div>}</dl></article></div></section>
      <div class="columns"><section class="panel"><h2>Related reports <span>{{ item.relatedReports.length }}</span></h2>@if(!item.relatedReports.length){<p class="muted">No other reports on this target.</p>}@for(related of item.relatedReports;track related.reportId){<a class="related" [routerLink]="['/admin/reports',related.reportId]"><strong>{{ label(related.reasonCode) }}</strong><span>{{ label(related.status) }} · {{ related.createdAt|date:'mediumDate' }}</span></a>}</section>
      <section class="panel"><h2>Current enforcement</h2><p class="readonly">Read-only context · report actions never enforce</p>@if(!item.currentEnforcementSummary.length){<p class="muted">No active enforcement is visible.</p>}@for(action of item.currentEnforcementSummary;track action.actionType+$index){<div class="enforcement"><strong>{{ action.actionType }}</strong><span>{{ action.scopes.join(', ') }}</span></div>}</section></div>
      <section class="panel timeline"><h2>Report timeline</h2>@for(event of item.auditTimeline;track event.eventId){<article><span class="dot"></span><div><strong>{{ label(event.eventType) }}</strong><p>{{ event.actorDisplayName }} · {{ event.occurredAt|date:'medium' }}</p>@if(event.reason){<p>{{ event.reason }}</p>}</div></article>}</section>
      <aside class="actions-panel"><div><h2>Triage controls</h2><p>{{ capabilities().readOnlyReason || 'You own this report and may triage it.' }}</p></div><div class="action-buttons">@if(capabilities().canClaim){<button (click)="claim()">Claim</button>}@if(capabilities().canRelease){<button class="secondary" (click)="release()">Release</button>}</div>
        @if(capabilities().canChangeSeverity){<form (ngSubmit)="changeSeverity()"><label><span>Severity</span><select name="severity" [(ngModel)]="severity">@for(value of severities;track value){<option [value]="value">{{ value }}</option>}</select></label><label><span>Reason</span><input name="severityReason" [(ngModel)]="severityReason" maxlength="1000" required></label><button type="submit">Update severity</button></form>}
        @if(capabilities().canDismiss){<form (ngSubmit)="dismiss()"><label><span>Dismissal reason</span><select name="dismissCode" [(ngModel)]="dismissCode"><option value="NO_VIOLATION_FOUND">No violation found</option><option value="DUPLICATE">Duplicate</option><option value="INSUFFICIENT_INFORMATION">Insufficient information</option><option value="INVALID_REPORT">Invalid report</option><option value="TARGET_ALREADY_UNAVAILABLE">Target already unavailable</option><option value="OTHER">Other</option></select></label><label><span>Explanation</span><input name="dismissReason" [(ngModel)]="dismissReason" maxlength="1000" required></label><button type="submit" class="danger">Dismiss report</button></form>}
        @if(capabilities().canMarkReadyForInvestigation){<form (ngSubmit)="ready()"><label><span>Investigation rationale</span><input name="readyReason" [(ngModel)]="readyReason" maxlength="1000" required></label><button type="submit">Mark ready for investigation</button></form>}
      </aside>
      @if(item.investigationCase){<section class="panel case-link"><div><p class="eyebrow">Investigation case</p><h2>{{ item.investigationCase.title }}</h2><code>{{ item.investigationCase.caseId }} · {{ label(item.investigationCase.status) }}</code></div><a [routerLink]="['/admin/cases',item.investigationCase.caseId]">Open investigation case</a></section>}
      @if(capabilities().canCreateInvestigationCase||capabilities().canLinkInvestigationCase){<section class="panel promotion"><div><p class="eyebrow">Investigation handoff</p><h2>Promote this allegation</h2><p class="muted">Create a distinct human investigation or link this report to a case you currently own.</p></div>
        @if(capabilities().canCreateInvestigationCase){<form (ngSubmit)="createCase()"><label><span>Case title</span><input name="caseTitle" [(ngModel)]="caseTitle" maxlength="160" required></label><label><span>Initial severity</span><select name="caseSeverity" [(ngModel)]="caseSeverity"><option value="">Use report severity ({{ item.severity }})</option>@for(value of severities;track value){<option [value]="value">{{ value }}</option>}</select></label><button type="submit">Create investigation case</button></form>}
        @if(capabilities().canLinkInvestigationCase){<div class="case-search"><form (ngSubmit)="searchCases()"><label><span>Find my active case</span><input name="caseQuery" [(ngModel)]="caseQuery" maxlength="160" placeholder="Case ID, title, or target ID"></label><button type="submit" class="secondary">Search cases</button></form>@for(candidate of caseCandidates();track candidate.caseId){<button type="button" class="candidate" (click)="linkCase(candidate)"><strong>{{ candidate.title }}</strong><span>{{ candidate.safePrimaryTargetLabel }} · {{ candidate.severity }}</span><code>{{ candidate.caseId }}</code></button>}@if(caseSearchEmpty()){<p class="muted">No eligible cases assigned to you.</p>}</div>}
      </section>}@if(actionError()){<div class="state error" role="alert">{{ actionError() }}</div>}
    }</section>
  `,
  styles:[`
    .page{display:grid;gap:1rem;padding-bottom:2rem}header,.version,.evidence-heading,.action-buttons{display:flex;align-items:center;justify-content:space-between;gap:1rem}header a{color:var(--color-info);font-weight:800;text-decoration:none}h1,h2,p,dl{margin:0}h1,h2{font-family:var(--font-display);color:var(--color-text-primary)}h1{font-size:1.8rem}h2{font-size:1.05rem}.eyebrow{margin:.45rem 0 .2rem;color:var(--color-info);font-size:.72rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.chip{border-radius:999px;padding:.35rem .65rem;background:rgba(56,189,248,.1);color:var(--color-info);font-weight:900}
    .summary,.panel,.actions-panel,.state,.evidence{border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-bg-secondary);padding:1rem}.summary dl{display:grid;grid-template-columns:repeat(6,1fr);gap:.75rem}.summary dt,.evidence dt{color:var(--color-text-muted);font-size:.72rem;text-transform:uppercase}.summary dd,.evidence dd{margin:.25rem 0 0;color:var(--color-text-primary);overflow-wrap:anywhere}.summary small{display:block;color:var(--color-text-muted)}.statement{margin-top:1rem;border-left:3px solid var(--color-warning);padding:.75rem;background:rgba(245,158,11,.08)}.statement span{color:var(--color-warning);font-size:.72rem;font-weight:900;text-transform:uppercase}.statement p{margin-top:.35rem;white-space:pre-wrap;line-height:1.55}
    .evidence{padding:0;overflow:hidden}.evidence-heading{display:grid;grid-template-columns:1fr auto 1fr;padding:1rem;border-bottom:1px solid var(--color-border)}.evidence-heading>span{color:var(--color-warning);font-size:1.5rem}.evidence-grid{display:grid;grid-template-columns:1fr 1fr}.evidence-grid article{padding:1rem;min-width:0}.evidence-grid article.current{border-left:2px solid var(--color-warning);background:rgba(245,158,11,.035)}.evidence-grid dl{display:grid;gap:.65rem;margin-top:.8rem}.timestamp,.muted,.readonly{color:var(--color-text-muted);font-size:.8rem}.columns{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.panel h2{display:flex;justify-content:space-between;margin-bottom:.75rem}.related,.enforcement{display:flex;justify-content:space-between;gap:.75rem;padding:.7rem 0;border-top:1px solid var(--color-border);color:var(--color-text-primary);text-decoration:none}.related span,.enforcement span{color:var(--color-text-muted)}.readonly{margin-top:-.55rem;margin-bottom:.75rem}.timeline article{position:relative;display:grid;grid-template-columns:16px 1fr;gap:.65rem;padding:.6rem 0}.dot{width:9px;height:9px;margin-top:.25rem;border-radius:50%;background:var(--color-info)}.timeline article p{color:var(--color-text-muted);font-size:.82rem;margin-top:.2rem}
    .actions-panel{display:grid;grid-template-columns:minmax(180px,.65fr) 1fr 1fr 1fr;gap:1rem;border-color:rgba(56,189,248,.45)}.actions-panel>div>p{margin-top:.35rem;color:var(--color-text-secondary)}form{display:grid;gap:.55rem;padding-left:1rem;border-left:1px solid var(--color-border)}label{display:grid;gap:.3rem;color:var(--color-text-muted);font-size:.75rem;font-weight:850}input,select{min-height:40px;border:1px solid var(--color-border);border-radius:var(--radius-md);padding:.55rem;background:var(--color-bg-primary);color:var(--color-text-primary);font:inherit}button{min-height:40px;border:0;border-radius:var(--radius-md);padding:.6rem .85rem;background:var(--color-accent);color:#07111f;font:inherit;font-weight:850;cursor:pointer}.secondary{border:1px solid var(--color-border);background:var(--color-bg-primary);color:var(--color-text-primary)}.danger{background:var(--color-danger);color:#fff}.state{color:var(--color-text-secondary)}.state.error{color:var(--color-danger)}code{font-size:.75rem}.case-link{display:flex;align-items:center;justify-content:space-between;gap:1rem;border-color:rgba(56,189,248,.45)}.case-link a{border-radius:var(--radius-md);padding:.65rem .9rem;background:var(--color-accent);color:#07111f;font-weight:900;text-decoration:none}.promotion{display:grid;grid-template-columns:.8fr 1fr 1fr;gap:1rem;border-color:rgba(245,158,11,.4)}.promotion>form,.case-search form{padding-left:1rem;border-left:1px solid var(--color-border)}.case-search{display:grid;gap:.5rem}.candidate{display:grid;text-align:left;background:var(--color-bg-primary);color:var(--color-text-primary);border:1px solid var(--color-border)}.candidate span,.candidate code{color:var(--color-text-muted);font-size:.72rem}.muted{color:var(--color-text-muted)}
    @media(max-width:950px){.summary dl{grid-template-columns:repeat(3,1fr)}.actions-panel,.promotion{grid-template-columns:1fr 1fr}.actions-panel form{padding:0;border:0}}@media(max-width:650px){header,.version,.case-link{align-items:flex-start;flex-direction:column}.summary dl,.columns,.evidence-grid,.actions-panel,.promotion{grid-template-columns:1fr}.promotion>form,.case-search form{padding:0;border:0}.evidence-grid article.current{border-left:0;border-top:2px solid var(--color-warning)}.evidence-heading{grid-template-columns:1fr}.evidence-heading>span{transform:rotate(90deg);justify-self:center}.related,.enforcement{flex-direction:column}}
  `]
})
export class AdminReportDetailComponent implements OnInit{
  private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly reports=inject(ReportService);private readonly cases=inject(InvestigationCaseService);private readonly toast=inject(ToastService);private reportId='';
  readonly report=signal<AdminReportDetail|null>(null);readonly loading=signal(true);readonly errorMsg=signal('');readonly actionError=signal('');readonly caseCandidates=signal<InvestigationCaseSummary[]>([]);readonly caseSearchEmpty=signal(false);readonly severities:ReportSeverity[]=['LOW','MEDIUM','HIGH','CRITICAL'];
  severity:ReportSeverity='MEDIUM';severityReason='';dismissCode='NO_VIOLATION_FOUND';dismissReason='';readyReason='';caseTitle='';caseSeverity:ReportSeverity|''='';caseQuery='';
  ngOnInit(){this.reportId=this.route.snapshot.paramMap.get('reportId')||'';this.load()} capabilities(){return reportAdminCapabilities(this.report())}
  load(){this.loading.set(true);this.errorMsg.set('');this.reports.detail(this.reportId).subscribe({next:value=>{this.report.set(value);this.severity=value.severity;this.loading.set(false)},error:error=>{this.loading.set(false);this.errorMsg.set(error.status===403?'You do not have permission to read this report.':'Report could not be loaded.')}})}
  claim(){this.mutate(()=>this.reports.claim(this.reportId,this.version()),'Report claimed.')}release(){this.mutate(()=>this.reports.release(this.reportId,this.version()),'Report released.')}
  changeSeverity(){if(!this.severityReason.trim())return;this.mutate(()=>this.reports.severity(this.reportId,this.version(),this.severity,this.severityReason.trim()),'Severity updated.');this.severityReason=''}
  dismiss(){if(!this.dismissReason.trim())return;this.mutate(()=>this.reports.dismiss(this.reportId,this.version(),this.dismissCode,this.dismissReason.trim()),'Report dismissed.')}
  ready(){if(!this.readyReason.trim())return;this.mutate(()=>this.reports.ready(this.reportId,this.version(),this.readyReason.trim()),'Report is ready for future investigation.')}
  createCase(){if(!this.caseTitle.trim())return;this.actionError.set('');this.reports.createInvestigationCase(this.reportId,this.caseTitle.trim(),this.caseSeverity||null,this.version()).subscribe({next:item=>{this.toast.success('Investigation case created.');this.router.navigate(['/admin/cases',item.caseId])},error:error=>this.caseActionError(error)})}
  searchCases(){this.caseSearchEmpty.set(false);this.cases.search({q:this.caseQuery.trim()||undefined,status:'UNDER_INVESTIGATION',assignment:'ASSIGNED_TO_ME',page:0,size:20,sort:'updatedAt,desc'}).subscribe({next:page=>{this.caseCandidates.set(page.items);this.caseSearchEmpty.set(!page.items.length)},error:error=>this.caseActionError(error)})}
  linkCase(candidate:InvestigationCaseSummary){this.actionError.set('');this.cases.linkReport(candidate.caseId,this.reportId,candidate.version,this.version()).subscribe({next:item=>{this.toast.success('Report linked to investigation case.');this.router.navigate(['/admin/cases',item.caseId])},error:error=>this.caseActionError(error)})}
  label(value:string){return value.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase())}value(object:Record<string,unknown>,key:string){return this.display(object?.[key])}
  evidenceLabel(key:string){return reportEvidenceLabel(key)} evidenceTimestamp(key:string,value:unknown){return isReportEvidenceTimestamp(key,value)} rawEvidenceValue(value:unknown){return rawReportEvidenceValue(value)} timestampValue(value:unknown){return typeof value==='string'||typeof value==='number'||value instanceof Date?value:null}
  display(value:unknown){if(value===null||value===undefined||value==='')return 'Not available';if(Array.isArray(value))return value.length?value.join(', '):'None';if(typeof value==='object')return JSON.stringify(value);return String(value)}
  private version(){return this.report()?.version??-1}private caseActionError(error:any){if(error.status===409){this.actionError.set('The report or case changed. Refresh and try again.');this.load()}else if(error.status===403)this.actionError.set('You do not have permission for this action.');else this.actionError.set(error.error?.error?.message||'The investigation action could not be completed.')}private mutate(call:()=>ReturnType<ReportService['claim']>,message:string){this.actionError.set('');call().subscribe({next:value=>{this.report.set(value);this.severity=value.severity;this.toast.success(message)},error:error=>{if(error.status===409){this.actionError.set('Report changed while you were working. The latest state has been loaded.');this.load()}else if(error.status===403)this.actionError.set('You do not have permission for this action.');else this.actionError.set('The report action could not be completed.')}})}
}
