import { DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AppealAssignment, AppealPage, AppealReason, AppealStatus } from '../../core/models/appeal.model';
import { ReportTargetType } from '../../core/models/report.model';
import { AppealService } from '../../core/services/appeal.service';

@Component({selector:'app-admin-appeal-inbox',standalone:true,imports:[DatePipe,FormsModule,RouterLink],template:`
  <section class="page"><header><div><p class="eyebrow">Trust & Safety workspace</p><h1>Appeal inbox</h1><p>Second-review requests tied to one specific enforcement action.</p></div><span class="count">{{page()?.totalElements||0}} appeals</span></header>
  <nav class="tabs" aria-label="Appeal assignment views">@for(tab of tabs;track tab.value){<button type="button" [attr.aria-pressed]="assignment===tab.value" [class.active]="assignment===tab.value" (click)="selectAssignment(tab.value)">{{tab.label}}</button>}</nav>
  <form class="filters" (ngSubmit)="apply()"><label><span>Search</span><input name="q" [(ngModel)]="query" placeholder="Appeal, enforcement, or target ID"></label><label><span>Status</span><select name="status" [(ngModel)]="status"><option value="">All statuses</option>@for(v of statuses;track v){<option [value]="v">{{label(v)}}</option>}</select></label><label><span>Target</span><select name="target" [(ngModel)]="targetType"><option value="">All targets</option>@for(v of targetTypes;track v){<option [value]="v">{{label(v)}}</option>}</select></label><label><span>Reason</span><select name="reason" [(ngModel)]="reason"><option value="">All reasons</option>@for(v of reasons;track v){<option [value]="v">{{label(v)}}</option>}</select></label><button>Apply filters</button></form>
  @if(loading()){<div class="state">Loading appeals…</div>}@else if(error()){<div class="state error" role="alert">{{error()}} <button type="button" (click)="load()">Retry</button></div>}@else if(!page()?.items?.length){<div class="state"><strong>No appeals match this view.</strong><p>New actor appeals will appear here.</p></div>}@else{<div class="table-wrap"><table><thead><tr><th>Appeal</th><th>Target</th><th>Original action</th><th>Reason</th><th>Status</th><th>Assignment</th><th>Submitted</th></tr></thead><tbody>@for(item of page()?.items;track item.appealId){<tr><td><a [routerLink]="['/admin/appeals',item.appealId]"><strong>{{item.appealId}}</strong><code>{{item.enforcementActionId}}</code></a></td><td><span class="type">{{label(item.targetType)}}</span><strong>{{item.safeTargetLabel}}</strong><code>{{item.targetId}}</code></td><td><span class="action">{{label(item.actionType)}}</span></td><td>{{label(item.appealReasonCode)}}</td><td><span class="status">{{label(item.status)}}</span></td><td>{{item.assignedAdminId||'Unassigned'}}</td><td>{{item.submittedAt|date:'medium'}}</td></tr>}</tbody></table></div><footer><button [disabled]="(page()?.page||0)===0" (click)="move(-1)">Previous</button><span>Page {{(page()?.page||0)+1}} of {{page()?.totalPages||1}}</span><button [disabled]="(page()?.page||0)+1 >= (page()?.totalPages||1)" (click)="move(1)">Next</button></footer>}</section>
`,styles:[`
  .page{display:grid;gap:1rem}header{display:flex;justify-content:space-between;align-items:end;gap:1rem}h1,p{margin:0}h1{font-family:var(--font-display);font-size:2rem}header p:last-child{margin-top:.35rem;color:var(--color-text-secondary)}.eyebrow{color:#a78bfa!important;font-size:.72rem;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.count,.type,.action,.status{display:inline-flex;border-radius:999px;padding:.3rem .55rem;background:rgba(167,139,250,.12);color:#a78bfa;font-size:.72rem;font-weight:900}.tabs{display:flex;gap:.4rem;overflow:auto}.tabs button{white-space:nowrap;border:1px solid var(--color-border);border-radius:999px;background:var(--color-bg-secondary);color:var(--color-text-secondary);padding:.55rem .85rem;font:inherit;font-weight:800;cursor:pointer}.tabs button.active{border-color:#a78bfa;color:#c4b5fd;background:rgba(167,139,250,.1)}.filters{display:grid;grid-template-columns:2fr repeat(3,1fr) auto;gap:.65rem;padding:1rem;border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-bg-secondary)}label{display:grid;gap:.3rem;color:var(--color-text-muted);font-size:.72rem;font-weight:850}input,select,.filters button,footer button,.state button{min-height:40px;border:1px solid var(--color-border);border-radius:var(--radius-md);padding:.55rem .7rem;background:var(--color-bg-primary);color:var(--color-text-primary);font:inherit}.filters button{align-self:end;border:0;background:#7c3aed;color:white;font-weight:900}.table-wrap{overflow:auto;border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-bg-secondary)}table{width:100%;border-collapse:collapse;min-width:1050px}th,td{padding:.85rem;text-align:left;border-bottom:1px solid var(--color-border);vertical-align:top}th{color:var(--color-text-muted);font-size:.7rem;text-transform:uppercase}td{color:var(--color-text-secondary);font-size:.84rem}td a,td>strong,td code{display:block}td a{color:var(--color-text-primary);text-decoration:none}td code{margin-top:.3rem;color:var(--color-text-muted);font-size:.68rem}.type{margin-bottom:.3rem}.state{padding:2rem;text-align:center;border:1px dashed var(--color-border);border-radius:var(--radius-lg);color:var(--color-text-secondary)}.state.error{color:var(--color-danger)}footer{display:flex;justify-content:flex-end;align-items:center;gap:.7rem;color:var(--color-text-muted)}footer button:disabled{opacity:.45}@media(max-width:850px){header{align-items:flex-start;flex-direction:column}.filters{grid-template-columns:1fr 1fr}}@media(max-width:560px){.filters{grid-template-columns:1fr}}
`]})
export class AdminAppealInboxComponent implements OnInit{
  private readonly service=inject(AppealService);readonly page=signal<AppealPage|null>(null);readonly loading=signal(true);readonly error=signal('');
  readonly tabs:{label:string;value:AppealAssignment}[]=[{label:'Unassigned',value:'UNASSIGNED'},{label:'Assigned to me',value:'ASSIGNED_TO_ME'},{label:'Assigned',value:'ASSIGNED'},{label:'All appeals',value:'ALL'}];
  readonly statuses:AppealStatus[]=['SUBMITTED','UNDER_REVIEW','UPHOLD_RECOMMENDED','MODIFY_RECOMMENDED','REVOKE_RECOMMENDED','UPHELD','MODIFIED','REVOKED'];readonly targetTypes:ReportTargetType[]=['USER','BUSINESS','LISTING'];readonly reasons:AppealReason[]=['DECISION_INCORRECT','NEW_EVIDENCE','ACCOUNT_COMPROMISED','MISIDENTIFICATION','ACTION_TOO_SEVERE','POLICY_MISAPPLIED','OTHER'];
  assignment:AppealAssignment='UNASSIGNED';query='';status:AppealStatus|''='';targetType:ReportTargetType|''='';reason:AppealReason|''='';private pageIndex=0;
  ngOnInit(){this.load()}selectAssignment(v:AppealAssignment){this.assignment=v;this.pageIndex=0;this.load()}apply(){this.pageIndex=0;this.load()}move(v:number){this.pageIndex+=v;this.load()}
  load(){this.loading.set(true);this.error.set('');this.service.search({q:this.query.trim()||undefined,targetType:this.targetType,status:this.status,reasonCode:this.reason,assignment:this.assignment,page:this.pageIndex,size:25,sort:'submittedAt,desc'}).subscribe({next:v=>{this.page.set(v);this.loading.set(false)},error:e=>{this.loading.set(false);this.error.set(e.status===403?'You do not have permission to read appeals.':'Appeals could not be loaded.')}})}
  label(v:string){return v.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase())}
}
