import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DisputeDetail, DisputeResolution } from '../../core/models/order-dispute.model';
import { OrderDisputeService } from '../../core/services/order-dispute.service';

@Component({selector:'app-admin-dispute-detail',standalone:true,imports:[FormsModule,RouterLink,DatePipe,CurrencyPipe],template:`
<section class="page"><a routerLink="/admin/disputes">Back to disputes</a>@if(error()){<p class="card error" role="alert">{{error()}}</p>}@else if(!detail()){<p class="card">Loading dispute…</p>}@else if(detail();as d){
<header><div><p>Transaction dispute</p><h1>{{d.summary.disputeId}}</h1><span>Version {{d.summary.version}} · {{d.summary.createdAt|date:'medium'}}</span></div><strong class="status">{{label(d.summary.status)}}</strong></header>
@if(d.capabilities.readOnlyReason){<p class="notice">{{d.capabilities.readOnlyReason}}</p>}
<div class="layout"><div class="stack"><article class="card"><h2>Dispute summary</h2><p>{{d.description}}</p><dl><div><dt>Reason</dt><dd>{{label(d.summary.reasonCode)}}</dd></div><div><dt>Priority</dt><dd>{{label(d.summary.priority)}}</dd></div><div><dt>Order</dt><dd><a [routerLink]="['/admin/orders',d.summary.orderId]">{{d.summary.orderId}}</a></dd></div><div><dt>Buyer</dt><dd><a [routerLink]="d.buyerAdminPath">{{d.summary.buyerUserId}}</a></dd></div><div><dt>Business</dt><dd><a [routerLink]="d.businessAdminPath">{{d.summary.businessId}}</a></dd></div><div><dt>Payment/refund</dt><dd>{{label(d.paymentStatus)}} · refunded {{d.alreadyRefundedAmount|currency:d.summary.currency}} · refundable {{d.currentlyRefundableAmount|currency:d.summary.currency}}</dd></div><div><dt>Inventory</dt><dd>{{label(d.inventoryReservationStatus||'unavailable')}} · release {{label(d.inventoryReleaseStatus)}}</dd></div><div><dt>Fulfillment</dt><dd>{{label(d.fulfillmentStatus)}} @if(d.shipment){· {{d.shipment.carrierDisplayName}} / {{d.shipment.trackingNumber}}}</dd></div></dl></article>
<article class="card"><h2>Purchase-time snapshots</h2>@for(item of d.disputedItems;track item.itemId){<div class="item"><span><strong>{{item.titleAtPurchase}}</strong><small>{{item.skuAtPurchase||'No SKU'}} · {{label(item.conditionAtPurchase)}} · Qty {{item.quantity}}</small></span><strong>{{item.lineTotal|currency:item.currency}}</strong></div>}</article>
<article class="card"><h2>Current listing state</h2>@for(item of d.disputedItems;track item.itemId){<div class="item"><span><strong>{{item.currentListing?.title||'Current listing unavailable'}}</strong><small>@if(item.currentListing){Status {{label(item.currentListing.status)}} · {{item.currentListing.price|currency:item.currentListing.currency}} · version {{item.currentListing.version}}}</small></span>@if(item.adminPath){<a [routerLink]="item.adminPath">Open listing admin</a>}</div>}</article>
<article class="card"><h2>Participant statements</h2>@for(s of d.statements;track s.id){<div class="entry"><strong>{{label(s.authorType)}}</strong><p>{{s.body}}</p><small>{{s.createdAt|date:'medium'}}</small></div>}</article>
<article class="card"><h2>Internal notes</h2>@for(n of d.internalNotes;track n.id){<div class="entry"><strong>{{n.authorDisplayName||n.authorAdminId}}</strong><p>{{n.body}}</p><small>{{n.createdAt|date:'medium'}}</small></div>}@if(d.capabilities.canAddNote){<form (ngSubmit)="addNote()"><textarea name="note" [(ngModel)]="note" maxlength="4000" required></textarea><button>Add internal note</button></form>}</article>
<article class="card"><h2>Audit timeline</h2>@for(e of d.timeline;track e.eventId){<div class="timeline"><span>{{e.occurredAt|date:'medium'}}</span><strong>{{label(e.eventType)}}</strong><small>{{e.reason}}</small></div>}</article></div>
<aside class="stack"><section class="card actions"><h2>Admin actions</h2>@if(d.capabilities.canClaim){<button (click)="claim()">Claim dispute</button>}@if(d.capabilities.canRelease){<button class="secondary" (click)="release()">Release</button>}@if(d.capabilities.canInvestigate){<label>Priority<select [(ngModel)]="priority"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Change reason<input [(ngModel)]="priorityReason"></label><button (click)="changePriority()">Update priority</button><hr><label>Request information from<select [(ngModel)]="party"><option value="BUYER">Buyer</option><option value="SELLER">Seller</option></select></label><textarea [(ngModel)]="information" placeholder="Explain what is needed"></textarea><button [disabled]="!d.capabilities.canRequestBuyerInformation&&!d.capabilities.canRequestSellerInformation" (click)="requestInfo()">Request information</button>}@if(d.capabilities.canMarkReadyForDecision){<hr><label>Decision readiness reason<textarea [(ngModel)]="readyReason"></textarea></label><button (click)="ready()">Mark ready for decision</button>}</section>
@if(d.capabilities.canResolve){<section class="card resolution"><h2>Resolve dispute</h2><label>Outcome<select [(ngModel)]="resolution"><option value="RESOLVED_NO_ACTION">No action</option><option value="RETURN_APPROVED">Return approved</option><option value="REFUND_RECOMMENDED">Full refund recommended</option><option value="PARTIAL_REFUND_RECOMMENDED">Partial refund recommended</option></select></label><label>Reason code<input [(ngModel)]="resolutionCode"></label><label>Decision reason<textarea [(ngModel)]="resolutionReason"></textarea></label>@if(resolution.includes('REFUND')){<label>Recommended amount<input type="number" step="0.01" [(ngModel)]="amount"></label><p class="warning"><strong>Recommendation only.</strong> This does not issue a refund. Currently refundable: {{d.currentlyRefundableAmount|currency:d.summary.currency}}</p>}@if(resolution==='RETURN_APPROVED'){<label>Return instructions<textarea [(ngModel)]="returnInstructions"></textarea></label><label>Return deadline<input type="datetime-local" [(ngModel)]="returnDeadline"></label>}<button class="danger" (click)="resolve()">Record final decision</button></section>}
<section class="card"><h2>Trust & Safety</h2><p>Transaction resolution does not create enforcement.</p>@for(path of d.trustAndSafetyPaths;track path){<a [routerLink]="path">View related operations</a>}</section></aside></div>}
</section>`,styles:[`.page{display:grid;gap:1rem}.page>header{display:flex;justify-content:space-between;gap:1rem;align-items:start}.page>header p{color:var(--color-info);font-weight:800;text-transform:uppercase}.status,.notice{padding:.55rem .75rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}.layout{display:grid;grid-template-columns:1fr 330px;gap:1rem;align-items:start}.stack,.card,.actions,.resolution,form{display:grid;gap:.75rem}.card{padding:1rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}dl div,.item{display:flex;justify-content:space-between;gap:1rem;padding:.55rem 0;border-bottom:1px solid var(--color-border)}dd{margin:0}.item span{display:grid}.entry{padding:.75rem;border-left:3px solid var(--color-info);background:var(--color-bg-primary)}.entry p{white-space:pre-wrap}.timeline{display:grid;grid-template-columns:150px 1fr;gap:.5rem}.timeline small{grid-column:2}label{display:grid;gap:.3rem;font-weight:700}input,select,textarea,button{padding:.65rem;border:1px solid var(--color-border);background:var(--color-bg-primary);color:var(--color-text-primary)}textarea{min-height:85px}button{font-weight:800;background:var(--color-info);color:#071118}.secondary{background:transparent;color:var(--color-text-primary)}.danger{background:var(--color-danger);color:#fff}.warning{padding:.75rem;border-left:4px solid #e2a13a;background:#382d18}.error{color:var(--color-danger)}@media(max-width:850px){.layout{grid-template-columns:1fr}}`]} )
export class AdminDisputeDetailComponent implements OnInit{private readonly route=inject(ActivatedRoute);private readonly service=inject(OrderDisputeService);readonly detail=signal<DisputeDetail|null>(null);readonly error=signal('');note='';priority='MEDIUM';priorityReason='Operational reassessment';party='BUYER';information='';readyReason='Review complete';resolution:DisputeResolution='RESOLVED_NO_ACTION';resolutionCode='ADMIN_REVIEW_COMPLETE';resolutionReason='';amount:number|null=null;returnInstructions='Return the disputed items using instructions agreed with the business.';returnDeadline='';private id='';ngOnInit(){this.id=this.route.snapshot.paramMap.get('disputeId')||'';this.load();}load(){this.service.adminDetail(this.id).subscribe({next:d=>{this.detail.set(d);this.priority=d.summary.priority;},error:e=>this.error.set(e?.error?.error?.message||'Dispute could not be loaded.')});}claim(){this.call(this.service.claim(this.id,this.v()));}release(){this.call(this.service.release(this.id,this.v()));}changePriority(){this.call(this.service.priority(this.id,this.v(),this.priority,this.priorityReason));}addNote(){this.call(this.service.note(this.id,this.note),()=>this.note='');}requestInfo(){this.call(this.service.information(this.id,this.v(),this.party,this.information),()=>this.information='');}ready(){this.call(this.service.ready(this.id,this.v(),this.readyReason));}resolve(){const d=this.detail();if(!d)return;const full=this.resolution==='REFUND_RECOMMENDED'?d.currentlyRefundableAmount:this.amount;this.call(this.service.resolve(this.id,{resolutionType:this.resolution,reasonCode:this.resolutionCode,reason:this.resolutionReason,recommendedRefundAmount:this.resolution.includes('REFUND')?full:null,returnInstructions:this.resolution==='RETURN_APPROVED'?this.returnInstructions:null,returnDeadline:this.resolution==='RETURN_APPROVED'&&this.returnDeadline?new Date(this.returnDeadline).toISOString():null,expectedVersion:d.summary.version}));}private v(){return this.detail()?.summary.version??-1;}private call(obs:any,done=()=>{}){this.error.set('');obs.subscribe({next:(d:DisputeDetail)=>{this.detail.set(d);done();},error:(e:any)=>{if(e.status===409)this.load();this.error.set(e?.error?.error?.message||'The action could not be completed.');}});}label(v:string){return(v||'').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}}
