import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, DestroyRef, OnInit, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AdminPage, AdminRefundSummary } from '../../core/models/admin-finance.model';
import { AdminFinanceService } from '../../core/services/admin-finance.service';

@Component({selector:'app-admin-refund-list',standalone:true,imports:[FormsModule,RouterLink,CurrencyPipe,DatePipe],template:`
<section class="page"><header><p>Financial operations</p><h1>Refunds</h1><span>Every refund source in one audit queue, including cancellation and business-return refunds.</span></header><form (ngSubmit)="load(0)"><label>Refund or payment<input name="q" [(ngModel)]="q" placeholder="Exact identifier"></label><label>Status<select name="status" [(ngModel)]="status"><option value="">All statuses</option><option>PENDING</option><option>PROCESSING</option><option>SUCCEEDED</option><option>FAILED</option></select></label><label>Provider<input name="provider" [(ngModel)]="provider" placeholder="Provider"></label><button>Apply filters</button></form>
@if(error()){<p class="state error" role="alert">{{error()}}</p>}@else if(!page()){<p class="state">Loading refund ledger…</p>}@else if(page();as p){<div class="table"><div class="row head"><span>Refund</span><span>Payment / order</span><span>Amount</span><span>Source</span><span>Status</span><span>Provider reference</span><span>Created</span></div>@for(r of p.content;track r.refundId){<a class="row" [routerLink]="['/admin/refunds',r.refundId]"><strong>{{short(r.refundId)}}</strong><span>{{short(r.paymentId)}}<small>{{short(r.orderId)}}</small></span><strong>{{r.amount|currency:r.currency}}</strong><span>{{label(r.source)}}</span><span [class.failed]="r.status==='FAILED'">{{label(r.status)}}</span><span>{{r.safeProviderRefundReference||'Not assigned'}}</span><span>{{r.createdAt|date:'short'}}</span></a>}@empty{<p class="state">No refunds match these filters.</p>}</div><nav><button [disabled]="p.page===0" (click)="load(p.page-1)">Previous</button><span>{{p.totalElements}} refunds · Page {{p.page+1}} of {{p.totalPages||1}}</span><button [disabled]="p.page+1>=p.totalPages" (click)="load(p.page+1)">Next</button></nav>}</section>`,styles:[`.page{display:grid;gap:1.2rem}header p{margin:0;color:var(--color-info);font:800 .75rem/1 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}h1{margin:.2rem 0;font-size:clamp(2rem,4vw,3.2rem)}header span{color:var(--color-text-muted)}form{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:.8rem;padding:1rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}label{display:grid;gap:.35rem;font-weight:750}input,select,button{padding:.65rem;border:1px solid var(--color-border);background:var(--color-bg-primary);color:var(--color-text-primary)}button{font-weight:800}.table{overflow:auto;border:1px solid var(--color-border)}.row{min-width:1040px;display:grid;grid-template-columns:1fr 1.25fr .8fr 1fr .75fr 1.25fr .9fr;gap:.8rem;padding:.8rem;border-bottom:1px solid var(--color-border);color:var(--color-text-primary);text-decoration:none;align-items:center}.row:not(.head):hover{background:rgba(56,189,248,.07)}.head{background:var(--color-bg-secondary);font:800 .75rem/1.2 ui-monospace,monospace;text-transform:uppercase}.row span{display:grid}.row small{color:var(--color-text-muted)}.failed,.error{color:var(--color-danger)}nav{display:flex;justify-content:flex-end;align-items:center;gap:1rem}.state{padding:1rem}@media(max-width:800px){form{grid-template-columns:1fr}}`]})
export class AdminRefundListComponent implements OnInit{private readonly service=inject(AdminFinanceService);private readonly route=inject(ActivatedRoute);private readonly destroy=inject(DestroyRef);readonly page=signal<AdminPage<AdminRefundSummary>|null>(null);readonly error=signal('');readonly statuses=['PENDING','PROCESSING','SUCCEEDED','FAILED'];q='';status='';provider='';ngOnInit(){this.route.queryParamMap.pipe(takeUntilDestroyed(this.destroy)).subscribe(params=>{const status=params.get('status');this.status=status&&this.statuses.includes(status)?status:'';this.load(0);});}load(page:number){this.error.set('');this.service.refunds({q:this.q,status:this.status,provider:this.provider,page,size:25,sort:'createdAt,desc'}).subscribe({next:v=>this.page.set(v),error:e=>this.error.set(e?.error?.error?.message||'Refunds could not be loaded.')});}short(v:string){return v.length>12?v.slice(0,10)+'…':v;}label(v:string){return(v||'').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}}
