export const ADMIN_PERMISSIONS = {
  DASHBOARD_READ: 'admin.dashboard.read',
  ANALYTICS_READ: 'admin.analytics.read',
  AUDIT_READ: 'admin.audit.read',
  BUSINESS_APPLICATION_READ: 'admin.business.application.read',
  BUSINESS_APPLICATION_DECIDE: 'admin.business.application.decide',
  LISTING_MODERATION_READ: 'admin.listing.moderation.read',
  LISTING_MODERATION_CLAIM: 'admin.listing.moderation.claim',
  LISTING_MODERATION_RESOLVE: 'admin.listing.moderation.resolve',
  LISTING_EDIT: 'admin.listing.edit',
  LISTING_REMOVE: 'admin.listing.remove',
  USER_READ: 'admin.user.read',
  USER_RESTRICT: 'admin.user.restrict',
  USER_SUSPEND: 'admin.user.suspend',
  USER_BAN: 'admin.user.ban',
  USER_REINSTATE: 'admin.user.reinstate',
  USER_PII_READ: 'admin.user.pii.read',
  BUSINESS_READ: 'admin.business.read',
  BUSINESS_RESTRICT: 'admin.business.restrict',
  BUSINESS_SUSPEND: 'admin.business.suspend',
  BUSINESS_BAN: 'admin.business.ban',
  BUSINESS_REINSTATE: 'admin.business.reinstate',
  LISTING_SUSPEND: 'admin.listing.suspend',
  LISTING_REINSTATE: 'admin.listing.reinstate',
  REPORT_READ: 'admin.report.read',
  REPORT_ASSIGN: 'admin.report.assign',
  REPORT_INVESTIGATE: 'admin.report.investigate',
  REPORT_RESOLVE: 'admin.report.resolve',
  APPEAL_READ: 'admin.appeal.read',
  APPEAL_ASSIGN: 'admin.appeal.assign',
  APPEAL_REVIEW: 'admin.appeal.review',
  APPEAL_RESOLVE: 'admin.appeal.resolve',
  ORDER_READ: 'admin.order.read',
  ORDER_CANCEL: 'admin.order.cancel',
  ORDER_MANAGE: 'admin.order.manage',
  DISPUTE_READ: 'admin.dispute.read',
  DISPUTE_ASSIGN: 'admin.dispute.assign',
  DISPUTE_INVESTIGATE: 'admin.dispute.investigate',
  DISPUTE_RESOLVE: 'admin.dispute.resolve',
  FINANCE_READ: 'admin.finance.read',
  REFUND_READ: 'admin.refund.read',
  REFUND_EXECUTE: 'admin.refund.execute',
  SUPPORT_READ: 'admin.support.read',
  SUPPORT_ASSIGN: 'admin.support.assign',
  SUPPORT_RESPOND: 'admin.support.respond',
  SUPPORT_RESOLVE: 'admin.support.resolve',
  SUPPORT_ESCALATE: 'admin.support.escalate',
  CATALOG_READ: 'admin.catalog.read',
  CATALOG_CATEGORY_MANAGE: 'admin.catalog.category.manage',
  CATALOG_ATTRIBUTE_MANAGE: 'admin.catalog.attribute.manage',
  CATALOG_POLICY_MANAGE: 'admin.catalog.policy.manage',
  SYSTEM_READ: 'admin.system.read',
  SYSTEM_RETRY: 'admin.system.retry',
  SEARCH_MAINTENANCE: 'admin.search.maintenance',
  FEATURE_READ: 'admin.feature.read',
  ROLE_READ: 'admin.role.read',
  ROLE_MANAGE: 'admin.role.manage',
  GOVERNANCE_READ: 'admin.governance.read',
  GOVERNANCE_ROLES_READ: 'admin.governance.roles.read',
  GOVERNANCE_ROLES_MANAGE: 'admin.governance.roles.manage',
  GOVERNANCE_ELEVATION_MANAGE: 'admin.governance.elevation.manage',
  GOVERNANCE_APPROVAL_READ: 'admin.governance.approval.read',
  GOVERNANCE_APPROVAL_REQUEST: 'admin.governance.approval.request',
  GOVERNANCE_APPROVAL_REVIEW: 'admin.governance.approval.review',
  GOVERNANCE_AUDIT_READ: 'admin.governance.audit.read',
} as const;

export type AdminPermission = typeof ADMIN_PERMISSIONS[keyof typeof ADMIN_PERMISSIONS];

export const ADMIN_ROLES = [
  'SUPER_ADMIN',
  'TRUST_AND_SAFETY_ADMIN',
  'BUSINESS_REVIEWER',
  'LISTING_MODERATOR',
  'SUPPORT_ADMIN',
  'CATALOG_ADMIN',
  'OPERATIONS_ADMIN',
  'GOVERNANCE_ADMIN',
  'USER_RESTRICTOR',
  'BUSINESS_RESTRICTOR',
  'AUDITOR',
  'AI_ADMIN_AGENT',
] as const;

export type AdminRole = typeof ADMIN_ROLES[number];
