import { DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { SupportUserPage } from '../../core/models/support.model';
import { SupportService } from '../../core/services/support.service';

@Component({selector:'app-support-ticket-list',standalone:true,imports:[RouterLink,DatePipe],template:`
<main class="support-page"><header><div><p class="eyebrow">Help center</p><h1>Your support requests</h1><span>Get help with your account, orders, payments, or selling.</span></div><a class="primary" routerLink="/support/new">New support request</a></header>
@if(error()){<p class="state error" role="alert">{{error()}}</p>}@else if(!page()){<p class="state">Loading your requests…</p>}@else if(page();as p){@if(!p.items.length){<section class="empty"><h2>No support requests yet</h2><p>If something is not working or you need help, start a request and our support team will respond here.</p><a class="primary" routerLink="/support/new">Ask for help</a></section>}@else{<section class="tickets" aria-label="Support requests">@for(ticket of p.items;track ticket.ticketId){<a [routerLink]="['/support',ticket.ticketId]" class="ticket"><span class="status" [class.waiting]="ticket.status==='WAITING_FOR_USER'">{{label(ticket.status)}}</span><div><small>{{label(ticket.category)}}</small><h2>{{ticket.subject}}</h2><p>Updated {{ticket.updatedAt|date:'medium'}}</p></div><strong aria-hidden="true">→</strong></a>}</section><nav><button [disabled]="p.page===0" (click)="load(p.page-1)">Previous</button><span>Page {{p.page+1}} of {{p.totalPages||1}}</span><button [disabled]="p.page+1>=p.totalPages" (click)="load(p.page+1)">Next</button></nav>}}</main>`,styles:[`
.support-page{max-width:900px;margin:0 auto;padding:2rem 1rem 4rem;display:grid;gap:1.25rem}.support-page>header{display:flex;justify-content:space-between;align-items:end;gap:1rem}.eyebrow{color:var(--color-info);font-weight:800;text-transform:uppercase;letter-spacing:.08em}.primary,button{display:inline-flex;justify-content:center;padding:.7rem 1rem;border:1px solid var(--color-info);background:var(--color-info);color:#071118;font-weight:800;text-decoration:none}.tickets{display:grid;gap:.75rem}.ticket{display:grid;grid-template-columns:140px 1fr auto;gap:1rem;align-items:center;padding:1rem;border:1px solid var(--color-border);background:var(--color-bg-secondary);color:var(--color-text-primary);text-decoration:none}.ticket:hover{border-color:var(--color-info)}.ticket h2{font-size:1.05rem;margin:.25rem 0}.ticket p,.ticket small{color:var(--color-text-muted)}.status{padding:.35rem .55rem;border:1px solid var(--color-border);text-align:center;font-size:.78rem;font-weight:800}.status.waiting{border-color:#e2a13a;color:#f2bd55}.empty,.state{padding:2rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}.error{color:var(--color-danger)}nav{display:flex;justify-content:flex-end;align-items:center;gap:1rem}nav button{background:transparent;color:var(--color-text-primary);border-color:var(--color-border)}@media(max-width:650px){.support-page>header{align-items:stretch;flex-direction:column}.ticket{grid-template-columns:1fr}.status{justify-self:start}}
`]})
export class SupportTicketListComponent implements OnInit{private readonly service=inject(SupportService);readonly page=signal<SupportUserPage|null>(null);readonly error=signal('');ngOnInit(){this.load(0);}load(page:number){this.error.set('');this.service.mine(page).subscribe({next:value=>this.page.set(value),error:e=>this.error.set(e?.error?.error?.message||'Your support requests could not be loaded.')});}label(value:string){return value.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}}
