import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { SupportCategory } from '../../core/models/support.model';
import { SupportService } from '../../core/services/support.service';

@Component({selector:'app-support-ticket-new',standalone:true,imports:[FormsModule,RouterLink],template:`
<main class="page"><a routerLink="/support">← Back to support</a><header><p>Help center</p><h1>How can we help?</h1><span>Tell us what happened. You can optionally include a relevant marketplace reference.</span></header>
@if(error()){<p class="error" role="alert">{{error()}}</p>}<form (ngSubmit)="submit()"><label>What do you need help with?<select name="category" [(ngModel)]="category" required><option value="ACCOUNT_HELP">Account</option><option value="ORDER_HELP">Order</option><option value="PAYMENT_HELP">Payment</option><option value="REFUND_HELP">Refund</option><option value="SELLER_HELP">Selling</option><option value="BUSINESS_VERIFICATION">Business verification</option><option value="LISTING_HELP">Listing</option><option value="TECHNICAL_ISSUE">Technical issue</option><option value="OTHER">Something else</option></select></label><label>Subject<input name="subject" [(ngModel)]="subject" minlength="5" maxlength="160" required placeholder="A short summary"></label><label>What happened?<textarea name="description" [(ngModel)]="description" minlength="20" maxlength="5000" required placeholder="Include the details our support team needs to understand the issue."></textarea></label><fieldset><legend>Relevant reference (optional)</legend><p>Add only a reference connected to your account or visible to you.</p><label>Order ID<input name="order" [(ngModel)]="linkedOrderId"></label><label>Business ID<input name="business" [(ngModel)]="linkedBusinessId"></label><label>Listing ID<input name="listing" [(ngModel)]="linkedListingId"></label></fieldset><button [disabled]="submitting()">{{submitting()?'Submitting…':'Submit support request'}}</button></form></main>`,styles:[`
.page{max-width:720px;margin:0 auto;padding:2rem 1rem 4rem;display:grid;gap:1rem}.page header p{color:var(--color-info);font-weight:800;text-transform:uppercase}form,fieldset,label{display:grid;gap:.45rem}form{gap:1rem;padding:1.25rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}label{font-weight:750}input,select,textarea,button{padding:.75rem;border:1px solid var(--color-border);background:var(--color-bg-primary);color:var(--color-text-primary);font:inherit}textarea{min-height:160px;resize:vertical}fieldset{grid-template-columns:1fr;gap:.75rem;border:1px solid var(--color-border);padding:1rem}fieldset p{color:var(--color-text-muted);margin:0}button{background:var(--color-info);color:#071118;font-weight:850}.error{padding:1rem;border-left:4px solid var(--color-danger);background:var(--color-bg-secondary);color:var(--color-danger)}
`]})
export class SupportTicketNewComponent{private readonly service=inject(SupportService);private readonly router=inject(Router);readonly submitting=signal(false);readonly error=signal('');category:SupportCategory='ACCOUNT_HELP';subject='';description='';linkedOrderId='';linkedBusinessId='';linkedListingId='';submit(){if(this.subject.trim().length<5||this.description.trim().length<20){this.error.set('Add a subject and a useful description before submitting.');return;}this.submitting.set(true);this.error.set('');this.service.create({category:this.category,subject:this.subject.trim(),description:this.description.trim(),linkedOrderId:this.linkedOrderId.trim()||null,linkedBusinessId:this.linkedBusinessId.trim()||null,linkedListingId:this.linkedListingId.trim()||null}).subscribe({next:value=>this.router.navigate(['/support',value.ticketId]),error:e=>{this.submitting.set(false);this.error.set(e?.error?.error?.message||'The support request could not be submitted.');}});}}
