import { DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { SupportUserDetail } from '../../core/models/support.model';
import { SupportService } from '../../core/services/support.service';

@Component({selector:'app-support-ticket-detail',standalone:true,imports:[DatePipe,FormsModule,RouterLink],template:`
<main class="page"><a routerLink="/support">← Your support requests</a>@if(error()){<p class="card error" role="alert">{{error()}}</p>}@else if(!ticket()){<p class="card">Loading support request…</p>}@else if(ticket();as t){<header><div><p>{{label(t.category)}}</p><h1>{{t.subject}}</h1><span>Opened {{t.createdAt|date:'medium'}} · Ticket {{short(t.ticketId)}}</span></div><strong class="status">{{label(t.status)}}</strong></header><article class="card"><h2>Your request</h2><p class="body">{{t.description}}</p>@if(t.linkedReferences.length){<div class="references"><h3>Related references</h3>@for(link of t.linkedReferences;track link.targetType+link.targetId){<span>{{label(link.targetType)}} · {{link.safeLabel}}</span>}</div>}</article><article class="card conversation"><h2>Conversation</h2>@if(!t.messages.length){<p class="muted">Support has not replied yet. Updates will appear here.</p>}@for(message of t.messages;track message.messageId){<div class="message" [class.mine]="message.author==='You'"><strong>{{message.author==='You'?'You':'Marketplace support'}}</strong><p>{{message.body}}</p><small>{{message.createdAt|date:'medium'}}</small></div>}@if(t.status!=='RESOLVED'){<form (ngSubmit)="reply()"><label>Your reply<textarea name="reply" [(ngModel)]="body" maxlength="5000" required></textarea></label><button [disabled]="sending()">{{sending()?'Sending…':'Send reply'}}</button></form>}</article>@if(t.status==='RESOLVED'){<article class="card resolution"><h2>Resolution</h2><strong>{{label(t.resolutionCode||'resolved')}}</strong><p>{{t.resolutionReason}}</p><small>{{t.resolvedAt|date:'medium'}}</small></article>}<article class="card"><h2>Ticket history</h2>@for(event of t.history;track event.eventId){<div class="event"><span>{{event.occurredAt|date:'medium'}}</span><strong>{{event.safeLabel}}</strong></div>}</article>}</main>`,styles:[`
.page{max-width:850px;margin:0 auto;padding:2rem 1rem 4rem;display:grid;gap:1rem}.page>header{display:flex;justify-content:space-between;gap:1rem;align-items:start}.page>header p{color:var(--color-info);font-weight:800;text-transform:uppercase}.status{padding:.5rem .7rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}.card{display:grid;gap:.75rem;padding:1.1rem;border:1px solid var(--color-border);background:var(--color-bg-secondary)}.body,.message p{white-space:pre-wrap}.references{display:flex;flex-wrap:wrap;gap:.5rem}.references h3{width:100%}.references span{padding:.4rem .6rem;border:1px solid var(--color-border)}.conversation{gap:1rem}.message{max-width:78%;padding:.85rem;border-left:4px solid var(--color-info);background:var(--color-bg-primary)}.message.mine{justify-self:end;border-left:0;border-right:4px solid #a78bfa}.message small,.muted{color:var(--color-text-muted)}form,label{display:grid;gap:.5rem}textarea,button{padding:.7rem;border:1px solid var(--color-border);background:var(--color-bg-primary);color:var(--color-text-primary);font:inherit}textarea{min-height:100px}button{justify-self:start;background:var(--color-info);color:#071118;font-weight:800}.resolution{border-left:4px solid #45c486}.event{display:grid;grid-template-columns:180px 1fr;gap:1rem;border-bottom:1px solid var(--color-border);padding:.5rem 0}.error{color:var(--color-danger)}@media(max-width:600px){.page>header{display:grid}.message{max-width:100%}.event{grid-template-columns:1fr}}
`]})
export class SupportTicketDetailComponent implements OnInit{private readonly route=inject(ActivatedRoute);private readonly service=inject(SupportService);readonly ticket=signal<SupportUserDetail|null>(null);readonly error=signal('');readonly sending=signal(false);body='';private id='';ngOnInit(){this.id=this.route.snapshot.paramMap.get('ticketId')||'';this.load();}load(){this.service.userDetail(this.id).subscribe({next:v=>this.ticket.set(v),error:e=>this.error.set(e?.error?.error?.message||'This support request is unavailable or not found.')});}reply(){const t=this.ticket();if(!t||!this.body.trim())return;this.sending.set(true);this.service.userReply(this.id,this.body.trim(),t.version).subscribe({next:v=>{this.ticket.set(v);this.body='';this.sending.set(false);},error:e=>{this.sending.set(false);this.error.set(e?.status===409?'The ticket changed. Reloading the latest version.':e?.error?.error?.message||'Your reply could not be sent.');if(e?.status===409)this.load();}});}short(v:string){return v.slice(0,8)+'…';}label(v:string){return v.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}}
