spring.application.name=payment-service
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
server.port=8084

# MySQL
spring.datasource.url=jdbc:mysql://${PAYMENT_DB_HOST:${MYSQL_HOST:localhost}}:${PAYMENT_DB_PORT:${MYSQL_PORT:3306}}/${PAYMENT_DB_NAME:payment_service}
spring.datasource.username=${PAYMENT_DB_USERNAME:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD:mysql}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
