export interface AdminPage<T> { content:T[]; page:number; size:number; totalElements:number; totalPages:number; sort:string; }
export interface FinanceCapabilities { canReadFinance:boolean; canReadRefund:boolean; canExecuteRefund:boolean; canRetryRefund:boolean; canViewPii:boolean; isRefundable:boolean; isRetryable:boolean; requiresDryRun:boolean; isReadOnly:boolean; readOnlyReason:string|null; }
export interface AdminPaymentSummary { paymentId:string; checkoutId:string; orderId:string|null; buyerUserId:string; buyerDisplayName:string; businessIds:string[]; businessDisplayNames:string[]; provider:string; safeProviderPaymentReference:string|null; paymentStatus:string; amount:number; capturedAmount:number; refundedAmount:number; pendingRefundAmount:number; refundableAmount:number; currency:string; refundCount:number; reconciliationState:string; createdAt:string; updatedAt:string; version:number; }
export interface AdminRefundSummary { refundId:string; paymentId:string; orderId:string; disputeId:string|null; amount:number; currency:string; status:string; provider:string; safeProviderRefundReference:string|null; source:string; initiatedByType:string; initiatedByAdminId:string|null; createdAt:string; updatedAt:string; completedAt:string|null; version:number; }
export interface FinanceTimelineEntry { eventId:string; occurredAt:string; eventType:string; actorType:string; actorId:string|null; actorDisplayName:string|null; previousState:string|null; newState:string|null; reasonCode:string|null; reason:string|null; correlationId:string|null; safeMetadata:Record<string,unknown>; }
export interface FinanceOrderContext { orderId:string; orderNumber:string; totalAmount:number; currency:string; businesses:Array<{businessId:string;displayName:string;storeNameAtPurchase:string;totalAmount:number;adminPath:string}>; purchaseItems:Array<{listingId:string;titleAtPurchase:string;quantity:number;lineTotal:number}>; adminPath:string; available:boolean; }
export interface DisputeFinanceContext { disputeId:string; businessId:string; resolutionType:string; recommendedRefundAmount:number; currency:string; resolutionReason:string; resolvedAt:string; adminPath:string; financiallyExecutable:boolean; }
export interface AdminPaymentDetail { payment:AdminPaymentSummary; orderContext:FinanceOrderContext; refunds:AdminRefundSummary[]; disputeRecommendations:DisputeFinanceContext[]; timeline:FinanceTimelineEntry[]; capabilities:FinanceCapabilities; }
export interface RefundAttempt { attemptNumber:number; operation:string; outcome:string; safeProviderReference:string|null; safeFailureCode:string|null; safeFailureSummary:string|null; createdAt:string; }
export interface AdminRefundDetail { refund:AdminRefundSummary; originalPaymentAmount:number; capturedAmount:number; refundedBeforeOperation:number; refundedTotal:number; currentlyRefundableAmount:number; attemptCount:number; latestAttempt:RefundAttempt|null; reconciliationState:string; safeFailureCode:string|null; safeFailureSummary:string|null; timeline:FinanceTimelineEntry[]; capabilities:FinanceCapabilities; }
export interface AdminRefundRequest { refundType:'FULL'|'PARTIAL'; amount:number|null; currency:string; reasonCode:string; reason:string; disputeId:string|null; expectedPaymentVersion:number; idempotencyKey:string; }
export interface AdminRefundPreview { paymentId:string; orderId:string; disputeId:string|null; refundType:string; requestedAmount:number; currency:string; capturedAmount:number; alreadyRefundedAmount:number; pendingRefundAmount:number; currentlyRefundableAmount:number; projectedRefundedTotal:number; projectedRemainingRefundableAmount:number; paymentStatus:string; recommendationComparison:string; warnings:string[]; allowed:boolean; denialReason:string|null; expectedPaymentVersion:number; }
export interface AdminRefundExecution { refundId:string; paymentId:string; orderId:string; disputeId:string|null; amount:number; currency:string; status:string; reconciliationState:string; paymentVersion:number; refundVersion:number; replayed:boolean; createdAt:string; completedAt:string|null; }
export interface AdminRefundApproval { outcome:string; approval:{approvalId:string;actionType:string;riskLevel:string;targetType:string;targetId:string;requiredApprovals:number;currentApprovals:number;status:string;createdAt:string;expiresAt:string;version:number}; approvalRequired:true; message:string; }
export type AdminRefundSubmission=AdminRefundExecution|AdminRefundApproval;
