export type DisputeStatus = 'OPEN'|'WAITING_FOR_BUYER'|'WAITING_FOR_SELLER'|'UNDER_ADMIN_REVIEW'|'READY_FOR_DECISION'|'RESOLVED_NO_ACTION'|'RETURN_APPROVED'|'REFUND_RECOMMENDED'|'PARTIAL_REFUND_RECOMMENDED';
export type DisputePriority = 'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';
export type DisputeResolution = 'RESOLVED_NO_ACTION'|'RETURN_APPROVED'|'REFUND_RECOMMENDED'|'PARTIAL_REFUND_RECOMMENDED';
export interface DisputeSummary { disputeId:string;orderId:string;businessGroupId:string;buyerUserId:string;businessId:string;reasonCode:string;priority:DisputePriority;status:DisputeStatus;assignedAdminId:string|null;disputedAmount:number;currency:string;createdAt:string;updatedAt:string;version:number; }
export interface DisputeItem { itemId:string;listingId:string;titleAtPurchase:string;skuAtPurchase:string|null;conditionAtPurchase:string;imageReferenceAtPurchase:string|null;quantity:number;unitPrice:number;lineTotal:number;currency:string;currentListing:{available:boolean;title:string;status:string;price:number;currency:string;version:number}|null;adminPath:string|null; }
export interface DisputeStatement { id:string;authorType:string;body:string;createdAt:string; }
export interface DisputeEvidence { id:string;authorType:string;referenceType:string;referenceId:string;label:string;createdAt:string; }
export interface DisputeNote { id:string;authorAdminId:string;authorDisplayName:string|null;body:string;createdAt:string; }
export interface DisputeTimeline { eventId:string;occurredAt:string;eventType:string;actorType:string;actorId:string|null;actorDisplayName:string|null;previousState:string|null;newState:string|null;reasonCode:string|null;reason:string|null;correlationId:string|null;requestId:string|null;safeMetadata:Record<string,unknown>; }
export interface DisputeCapabilities { canRead:boolean;canClaim:boolean;canRelease:boolean;canInvestigate:boolean;canAddNote:boolean;canRequestBuyerInformation:boolean;canRequestSellerInformation:boolean;canChangePriority:boolean;canMarkReadyForDecision:boolean;canResolve:boolean;isAssignedToMe:boolean;isAssignedToOther:boolean;isFinal:boolean;isReadOnly:boolean;readOnlyReason:string|null; }
export interface DisputeDetail { summary:DisputeSummary;openedByType:string;openedByUserId:string|null;description:string;disputedItems:DisputeItem[];statements:DisputeStatement[];evidence:DisputeEvidence[];internalNotes:DisputeNote[];timeline:DisputeTimeline[];resolution:{type:DisputeResolution;reasonCode:string;reason:string;recommendedRefundAmount:number|null;currency:string;returnInstructions:string|null;returnDeadline:string|null;resolvedAt:string}|null;currentlyRefundableAmount:number;alreadyRefundedAmount:number;orderStatus:string;paymentStatus:string;inventoryReservationStatus:string|null;inventoryReleaseStatus:string;fulfillmentStatus:string;shipment:{source:string;carrierDisplayName:string;serviceDisplayName:string;trackingNumber:string;status:string;shippedAt:string;deliveredAt:string|null}|null;cancellationStatus:string;buyerAdminPath:string|null;businessAdminPath:string|null;trustAndSafetyPaths:string[];capabilities:DisputeCapabilities; }
export interface DisputePage { content:DisputeSummary[];page:number;size:number;totalElements:number;totalPages:number;sort:string; }
export interface CreateDisputeRequest { businessGroupId:string;reasonCode:string;description:string;itemIds:string[];evidence:{referenceType:string;referenceId:string;label:string}[];idempotencyKey?:string; }
