export type OperationalStatus = 'HEALTHY'|'DEGRADED'|'UNAVAILABLE'|'UNKNOWN'|'PENDING'|'FAILED'|'DEAD_LETTER'|'TERMINAL'|'SUCCEEDED'|'SENT'|'ENABLED'|'DISABLED';
export interface ServiceHealth {serviceKey:string;displayName:string;status:OperationalStatus;checkedAt:string;responseLatencyMs:number|null;safeSummary:string;}
export interface JobSummary {jobId:string;jobType:string;ownerService:string;status:OperationalStatus;attemptCount:number;maxAttempts:number|null;createdAt:string;lastAttemptAt:string|null;nextAttemptAt:string|null;correlationId:string|null;safeFailureCode:string|null;safeFailureSummary:string|null;retryable:boolean;relatedTargetType:string|null;relatedTargetId:string|null;}
export interface OutboxSummary {eventId:string;ownerService:string;eventType:string;aggregateType:string;aggregateId:string;status:OperationalStatus;attemptCount:number;createdAt:string;lastAttemptAt:string|null;nextAttemptAt:string|null;correlationId:string|null;safeFailureCode:string|null;safeFailureSummary:string|null;retryable:boolean;}
export interface ReconciliationIssue {issueId:string;issueType:string;ownerService:string;targetType:string;targetId:string;localState:string;externalStateSafe:string|null;severity:string;status:string;lastCheckedAt:string|null;attemptCount:number;safeSummary:string;retryable:boolean;correlationId:string|null;}
export interface InventoryIssue {reservationId:string;orderId:string|null;listingId:string|null;quantity:number;status:string;createdAt:string;expiresAt:string;ageSeconds:number;issueType:string;safeSummary:string;retryable:boolean;}
export interface SearchIssue {workId:string;targetType:string;targetId:string;operationType:string;status:string;attemptCount:number;lastAttemptAt:string|null;safeFailureSummary:string|null;retryable:boolean;}
export interface SearchStatus {ownerService:string;status:string;pendingOperations:number;failedOperations:number;lastSuccessfulIndexingAt:string|null;indexVersion:string;safeSummary:string;issues:SearchIssue[];}
export interface FeatureState {featureKey:string;displayName:string;status:string;scope:string;source:string;lastChangedAt:string|null;mutable:boolean;safeSummary:string;}
export interface PageResponse<T>{items:T[];page:number;size:number;totalElements:number;totalPages:number;}
export interface OperationEvent {commandId:string;eventType:string;actorUserId:string;targetType:string;targetId:string;reason:string;outcome:string;correlationId:string;createdAt:string;safeMetadata:Record<string,string>;}
export interface CountPair {primary:number;secondary:number;}
export interface SystemSummary {generatedAt:string;serviceHealth:CountPair;jobs:CountPair;outbox:CountPair;reconciliationRequiresAttention:number;inventoryPotentiallyStuck:number;failedIndexOperations:number;featureWarnings:number;sourceWarnings:string[];recentOperations:OperationEvent[];}
export interface MaintenanceRequest {reason:string;expectedVersion?:number|null;idempotencyKey?:string|null;}
export interface MaintenancePreview {targetType:string;targetId:string;ownerService:string;commandType:string;currentState:string;allowed:boolean;denialReason:string|null;knownDependencies:string[];warnings:string[];expectedOperation:string;customerImpact:string;}
export interface MaintenanceResult {commandId:string;targetType:string;targetId:string;ownerService:string;commandType:string;result:'ACCEPTED'|'REJECTED'|'ALREADY_COMPLETED'|'NOT_RETRYABLE';replay:boolean;requestedAt:string;safeSummary:string;}
