spring.application.name=inventory-service
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
server.port=8082

# MySQL
spring.datasource.url=jdbc:mysql://${INVENTORY_DB_HOST:${MYSQL_HOST:localhost}}:${INVENTORY_DB_PORT:${MYSQL_PORT:3306}}/${INVENTORY_DB_NAME:inventory_service}
spring.datasource.username=${INVENTORY_DB_USERNAME:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD:mysql}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
