import { CurrencyPipe, DatePipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { DisputeDetail } from '../../core/models/order-dispute.model';
import { OrderDisputeService } from '../../core/services/order-dispute.service';

@Component({selector:'app-order-dispute',standalone:true,imports:[FormsModule,DatePipe,CurrencyPipe,RouterLink],template:`
<section class="page"><a [routerLink]="orderId?'/account/orders/'+orderId:'/account/orders'">Back to order</a>
@if(error()){<p class="card error" role="alert">{{error()}}</p>}
@if(createMode){<header><p>Transaction support</p><h1>Report a problem</h1><span>This dispute applies only to the selected store group.</span></header>
<form class="card" (ngSubmit)="create()"><label>Reason<select name="reason" [(ngModel)]="reason"><option value="ITEM_NOT_RECEIVED">Item not received</option><option value="ITEM_DAMAGED">Item damaged</option><option value="ITEM_NOT_AS_DESCRIBED">Item not as described</option><option value="WRONG_ITEM">Wrong item</option><option value="COUNTERFEIT_OR_INAUTHENTIC">Counterfeit or inauthentic</option><option value="MISSING_PARTS">Missing parts</option><option value="QUANTITY_INCORRECT">Quantity incorrect</option><option value="SELLER_FAILED_TO_FULFILL">Seller failed to fulfill</option><option value="RETURN_DISAGREEMENT">Return disagreement</option><option value="OTHER">Other</option></select></label><label>What happened?<textarea name="description" [(ngModel)]="description" maxlength="2000" required></textarea></label><p>No refund or enforcement is created when you submit this dispute.</p><button [disabled]="busy()">{{busy()?'Submitting…':'Submit dispute'}}</button></form>}
@else if(detail();as d){<header><p>{{label(d.summary.status)}}</p><h1>Dispute {{d.summary.disputeId}}</h1><span>Opened {{d.summary.createdAt|date:'medium'}}</span></header>
<section class="grid"><div class="stack"><article class="card"><h2>{{label(d.summary.reasonCode)}}</h2><p>{{d.description}}</p><dl><div><dt>Order</dt><dd>{{d.summary.orderId}}</dd></div><div><dt>Store group</dt><dd>{{d.summary.businessGroupId}}</dd></div><div><dt>Payment</dt><dd>{{label(d.paymentStatus)}}</dd></div></dl></article>
<article class="card"><h2>Purchase-time item snapshots</h2>@for(item of d.disputedItems;track item.itemId){<div class="item"><span><strong>{{item.titleAtPurchase}}</strong><small>{{item.skuAtPurchase||'No SKU'}} · Qty {{item.quantity}}</small></span><strong>{{item.lineTotal|currency:item.currency}}</strong></div>}</article>
<article class="card"><h2>Conversation</h2>@for(s of d.statements;track s.id){<div class="message"><strong>{{label(s.authorType)}}</strong><p>{{s.body}}</p><small>{{s.createdAt|date:'medium'}}</small></div>}@if(!d.capabilities.isFinal){<form (ngSubmit)="respond()"><label>Add information<textarea name="response" [(ngModel)]="response" maxlength="4000" required></textarea></label><button [disabled]="busy()">Respond</button></form>}</article></div>
<aside class="card"><h2>Resolution</h2>@if(d.resolution;as r){<strong>{{label(r.type)}}</strong><p>{{r.reason}}</p>@if(r.recommendedRefundAmount){<p>Recommended: {{r.recommendedRefundAmount|currency:r.currency}}</p><small>This is a recommendation only. No refund has been issued.</small>}@if(r.returnInstructions){<p>{{r.returnInstructions}}</p>}}@else{<p>An administrator has not recorded a final decision.</p>}<h3>Timeline</h3>@for(e of d.timeline;track e.eventId){<p><strong>{{label(e.eventType)}}</strong><br><small>{{e.occurredAt|date:'medium'}}</small></p>}</aside></section>}
</section>`,styles:[`.page{max-width:1050px;margin:auto;display:grid;gap:1rem}.page>header p{font-weight:900;color:#16735f;text-transform:uppercase}.card{display:grid;gap:.8rem;padding:1rem;border:1px solid var(--market-line);border-radius:8px;background:#fff}.grid{display:grid;grid-template-columns:1fr 300px;gap:1rem;align-items:start}.stack{display:grid;gap:1rem}label{display:grid;gap:.35rem;font-weight:800}textarea,select{padding:.65rem;border:1px solid var(--market-line)}textarea{min-height:110px}button{width:fit-content;padding:.7rem 1rem;border:0;background:#16735f;color:#fff;font-weight:900}.item,dl div{display:flex;justify-content:space-between;gap:1rem;padding:.6rem 0;border-bottom:1px solid var(--market-line)}.item span{display:grid}.message{padding:.7rem;border-left:3px solid #16735f;background:#f5faf8}.message p{white-space:pre-wrap}.error{color:#a83232}@media(max-width:760px){.grid{grid-template-columns:1fr}}`]} )
export class OrderDisputeComponent implements OnInit{
 private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly service=inject(OrderDisputeService);
 readonly detail=signal<DisputeDetail|null>(null);readonly error=signal('');readonly busy=signal(false);
 readonly orderId=this.route.snapshot.paramMap.get('orderId');readonly businessId=this.route.snapshot.paramMap.get('businessId');readonly disputeId=this.route.snapshot.paramMap.get('disputeId');readonly createMode=!!this.orderId&&!this.disputeId;
 reason='ITEM_NOT_AS_DESCRIBED';description='';response='';
 ngOnInit(){if(this.disputeId)this.load();}
 create(){const group=this.route.snapshot.queryParamMap.get('businessGroupId');if(!this.orderId||!group)return;this.busy.set(true);this.service.buyerCreate(this.orderId,{businessGroupId:group,reasonCode:this.reason,description:this.description,itemIds:[],evidence:[]}).subscribe({next:d=>this.router.navigate(['/account/disputes',d.summary.disputeId]),error:e=>{this.busy.set(false);this.error.set(e?.error?.error?.message||'Dispute could not be submitted.');}});}
 respond(){if(!this.disputeId)return;this.busy.set(true);const call=this.businessId?this.service.sellerStatement(this.businessId,this.disputeId,this.response):this.service.buyerStatement(this.disputeId,this.response);call.subscribe({next:d=>{this.detail.set(d);this.response='';this.busy.set(false);},error:e=>{this.busy.set(false);this.error.set(e?.error?.error?.message||'Information could not be added.');}});}
 private load(){if(!this.disputeId)return;const call=this.businessId?this.service.sellerDetail(this.businessId,this.disputeId):this.service.buyerDetail(this.disputeId);call.subscribe({next:d=>this.detail.set(d),error:e=>this.error.set(this.loadError(e))});}
 private loadError(error:unknown){if(error instanceof HttpErrorResponse&&(error.status===403||error.status===404))return'Dispute unavailable or not found.';return'Dispute could not be loaded. Try again.';}
 label(v:string){return(v||'').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
}
