ALTER TABLE notifications
    DROP CHECK chk_notification_type,
    DROP CHECK chk_notification_message_key,
    ADD CONSTRAINT chk_notification_type CHECK (type IN (
        'BUYER_ORDER_CONFIRMED','BUYER_ORDER_CANCELLED','BUYER_REFUND_COMPLETED',
        'BUYER_ORDER_ACCEPTED','BUYER_ORDER_PROCESSING','BUYER_ORDER_SHIPPED',
        'BUYER_ORDER_DELIVERED','SELLER_NEW_ORDER','SELLER_ORDER_CANCELLED','ORDER_CONFIRMED',
        'BUYER_RETURN_AUTHORIZED','BUYER_RETURN_RECEIVED','BUYER_RETURN_REFUND_COMPLETED',
        'SELLER_RETURN_REQUESTED')),
    ADD CONSTRAINT chk_notification_message_key CHECK (message_key IN (
        'BUYER_ORDER_CONFIRMED_V1','BUYER_ORDER_CANCELLED_V1','BUYER_REFUND_COMPLETED_V1',
        'BUYER_ORDER_ACCEPTED_V1','BUYER_ORDER_PROCESSING_V1','BUYER_ORDER_SHIPPED_V1',
        'BUYER_ORDER_DELIVERED_V1','SELLER_NEW_ORDER_V1','SELLER_ORDER_CANCELLED_V1','ORDER_CONFIRMED_V1',
        'BUYER_RETURN_AUTHORIZED_V1','BUYER_RETURN_RECEIVED_V1','BUYER_RETURN_REFUND_COMPLETED_V1',
        'SELLER_RETURN_REQUESTED_V1'));
