import { expect, Page, test } from '@playwright/test';

const PAYMENT='01KZPAYMENT000000000000001';
const REFUND='01KZREFUND000000000000001';
const ORDER='01KZORDER00000000000000001';

test('finance admin searches payment and confirms an exact dry-run refund',async({page})=>{let executed=false;await mockAdmin(page,['admin.finance.read','admin.refund.read','admin.refund.execute']);await page.route('**/api/v1/admin/payments?**',r=>r.fulfill({json:{content:[summary()],page:0,size:25,totalElements:1,totalPages:1,sort:'createdAt,desc'}}));await page.route(`**/api/v1/admin/payments/${PAYMENT}`,r=>r.fulfill({json:paymentDetail(true)}));await page.route(`**/api/v1/admin/payments/${PAYMENT}/refund/dry-run`,r=>r.fulfill({json:preview()}));await page.route(`**/api/v1/admin/payments/${PAYMENT}/refund`,async r=>{expect(r.request().headers()['idempotency-key']).toContain('admin-refund:');executed=true;await r.fulfill({json:{refundId:REFUND,paymentId:PAYMENT,orderId:ORDER,disputeId:null,amount:125,currency:'USD',status:'SUCCEEDED',reconciliationState:'IN_SYNC',paymentVersion:5,refundVersion:0,replayed:false,createdAt:'2026-08-19T01:00:00Z',completedAt:'2026-08-19T01:00:00Z'}});});await page.goto('/admin/payments');await expect(page.getByRole('heading',{name:'Payments'})).toBeVisible();await expect(page.getByText('$125.00 available')).toBeVisible();await page.goto(`/admin/payments/${PAYMENT}`);await page.getByRole('button',{name:'Review refund'}).click();await expect(page.getByRole('heading',{name:'Confirmation ledger'})).toBeVisible();await expect(page.getByText('Remaining after refund')).toBeVisible();await page.getByLabel(/I confirm this exact amount/).check();await page.getByRole('button',{name:/Issue.*refund/}).click();await expect.poll(()=>executed).toBe(true);await expect(page.getByText(`Refund ${REFUND}`)).toBeVisible();});

test('partial refund rejects zero and negative amounts before dry run',async({page})=>{let previews=0;await mockAdmin(page,['admin.finance.read','admin.refund.read','admin.refund.execute']);await page.route(`**/api/v1/admin/payments/${PAYMENT}`,r=>r.fulfill({json:paymentDetail(true)}));await page.route(`**/api/v1/admin/payments/${PAYMENT}/refund/dry-run`,r=>{previews++;return r.fulfill({json:preview()});});await page.goto(`/admin/payments/${PAYMENT}`);await page.getByLabel('Refund type').selectOption('PARTIAL');const amount=page.getByRole('spinbutton',{name:'Amount'});for(const value of ['0','-1']){await amount.fill(value);await page.getByRole('button',{name:'Review refund'}).click();await expect(page.getByRole('alert')).toHaveText('Enter a partial refund amount greater than zero.');}expect(previews).toBe(0);});

test('payment detail fits a narrow mobile viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await mockAdmin(page,['admin.finance.read','admin.refund.read','admin.refund.execute']);await page.route(`**/api/v1/admin/payments/${PAYMENT}`,r=>r.fulfill({json:paymentDetail(true)}));await page.goto(`/admin/payments/${PAYMENT}`);await expect(page.getByRole('heading',{name:'Issue a refund'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(()=>document.documentElement.clientWidth));});

test('refund reader is read-only and sees no execution control',async({page})=>{await mockAdmin(page,['admin.finance.read','admin.refund.read'],['AUDITOR']);await page.route(`**/api/v1/admin/payments/${PAYMENT}`,r=>r.fulfill({json:paymentDetail(false)}));await page.goto(`/admin/payments/${PAYMENT}`);await expect(page.getByText('Auditors can inspect but cannot issue refunds.')).toBeVisible();await expect(page.getByRole('button',{name:'Review refund'})).toHaveCount(0);});

test('failed uncertain refund is auditable and cannot be blindly retried',async({page})=>{await mockAdmin(page,['admin.finance.read','admin.refund.read']);await page.route(`**/api/v1/admin/refunds/${REFUND}`,r=>r.fulfill({json:refundDetail()}));await page.goto(`/admin/refunds/${REFUND}`);await expect(page.getByText('REFUND_PROVIDER_STATE_UNCERTAIN')).toBeVisible();await expect(page.getByText(/Automated retry is unavailable/)).toBeVisible();await expect(page.getByRole('button',{name:/retry/i})).toHaveCount(0);});

test('above-threshold refund creates approval without a refund result',async({page})=>{
 await mockAdmin(page,['admin.finance.read','admin.refund.read','admin.refund.execute']);
 await page.route(`**/api/v1/admin/payments/${PAYMENT}`,r=>r.fulfill({json:paymentDetail(true)}));
 await page.route(`**/api/v1/admin/payments/${PAYMENT}/refund/dry-run`,r=>r.fulfill({json:preview()}));
 let submissions=0;
 await page.route(`**/api/v1/admin/payments/${PAYMENT}/refund`,r=>{submissions++;return r.fulfill({status:202,json:{outcome:'PENDING_APPROVAL',approval:{approvalId:'01KZFINAPPROVAL000000000001',actionType:'LARGE_REFUND',riskLevel:'HIGH',targetType:'PAYMENT',targetId:PAYMENT,requiredApprovals:1,currentApprovals:0,status:'PENDING',createdAt:'2026-08-23T00:00:00Z',expiresAt:'2026-08-23T04:00:00Z',version:0},approvalRequired:true,message:'Independent approval is required before the refund can execute.'}});});
 await page.goto(`/admin/payments/${PAYMENT}`);
 await page.getByRole('button',{name:'Review refund'}).click();
 await page.getByLabel(/I confirm this exact amount/).check();
 await page.getByRole('button',{name:/Issue.*refund/}).click();
 await expect.poll(()=>submissions).toBe(1);
 await expect(page.getByText('Independent approval required')).toBeVisible();
 await expect(page.getByRole('link',{name:/Open approval/})).toBeVisible();
 await expect(page.getByText(`Refund ${REFUND}`)).toHaveCount(0);
});

async function mockAdmin(page:Page,permissions:string[],roles=['PLATFORM_ADMIN']){await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{authenticated:true,user:{subject:'01KZADMIN00000000000000001',email:'finance@msb.local',displayName:'Finance Admin',roles,expiresAt:null},csrf:{headerName:'X-XSRF-TOKEN',parameterName:'_csrf',token:'csrf'}}}));await page.route('**/api/v1/users/me',r=>r.fulfill({status:503,json:{error:{message:'Use session fallback.'}}}));await page.route('**/api/v1/admin/me',r=>r.fulfill({json:{data:{userId:'01KZADMIN00000000000000001',role:roles[0],roles,permissions,accountState:'ACTIVE'}}}));}
function summary(){return{paymentId:PAYMENT,checkoutId:'01KZCHECK00000000000000001',orderId:ORDER,buyerUserId:'01KZBUYER00000000000000001',buyerDisplayName:'Buyer One',businessIds:['01KZBUSIN00000000000000001'],businessDisplayNames:['Camera House'],provider:'FAKE_LOCAL_DEMO_V1',safeProviderPaymentReference:'fake_pi_safe',paymentStatus:'SUCCEEDED',amount:125,capturedAmount:125,refundedAmount:0,pendingRefundAmount:0,refundableAmount:125,currency:'USD',refundCount:0,reconciliationState:'IN_SYNC',createdAt:'2026-08-19T00:00:00Z',updatedAt:'2026-08-19T00:00:00Z',version:4};}
function capabilities(execute:boolean){return{canReadFinance:true,canReadRefund:true,canExecuteRefund:execute,canRetryRefund:false,canViewPii:false,isRefundable:true,isRetryable:false,requiresDryRun:true,isReadOnly:!execute,readOnlyReason:execute?null:'Auditors can inspect but cannot issue refunds.'};}
function paymentDetail(execute:boolean){return{payment:summary(),orderContext:{orderId:ORDER,orderNumber:'MSB-1001',totalAmount:125,currency:'USD',businesses:[{businessId:'01KZBUSIN00000000000000001',displayName:'Camera House',storeNameAtPurchase:'Camera House',totalAmount:125,adminPath:'/admin/businesses/01KZBUSIN00000000000000001'}],purchaseItems:[{listingId:'01KZLISTIN00000000000000001',titleAtPurchase:'Snapshot camera',quantity:1,lineTotal:125}],adminPath:`/admin/orders/${ORDER}`,available:true},refunds:[],disputeRecommendations:[],timeline:[],capabilities:capabilities(execute)};}
function preview(){return{paymentId:PAYMENT,orderId:ORDER,disputeId:null,refundType:'FULL',requestedAmount:125,currency:'USD',capturedAmount:125,alreadyRefundedAmount:0,pendingRefundAmount:0,currentlyRefundableAmount:125,projectedRefundedTotal:125,projectedRemainingRefundableAmount:0,paymentStatus:'SUCCEEDED',recommendationComparison:'No dispute recommendation linked.',warnings:[],allowed:true,denialReason:null,expectedPaymentVersion:4};}
function refundDetail(){return{refund:{refundId:REFUND,paymentId:PAYMENT,orderId:ORDER,disputeId:null,amount:25,currency:'USD',status:'FAILED',provider:'FAKE_LOCAL_DEMO_V1',safeProviderRefundReference:null,source:'HUMAN_ADMIN',initiatedByType:'HUMAN_ADMIN',initiatedByAdminId:'01KZADMIN00000000000000001',createdAt:'2026-08-19T00:00:00Z',updatedAt:'2026-08-19T00:00:00Z',completedAt:null,version:0},originalPaymentAmount:125,capturedAmount:125,refundedBeforeOperation:0,refundedTotal:0,currentlyRefundableAmount:125,attemptCount:1,latestAttempt:{attemptNumber:1,operation:'PARTIAL_REFUND',outcome:'UNCERTAIN',safeProviderReference:null,safeFailureCode:'REFUND_PROVIDER_STATE_UNCERTAIN',safeFailureSummary:'The provider outcome could not be confirmed.',createdAt:'2026-08-19T00:00:00Z'},reconciliationState:'REQUIRES_ATTENTION',safeFailureCode:'REFUND_PROVIDER_STATE_UNCERTAIN',safeFailureSummary:'The provider outcome could not be confirmed.',timeline:[],capabilities:{...capabilities(false),isRefundable:false,readOnlyReason:'Provider state requires manual reconciliation; automatic retry is unavailable.'}};}
