import { expect, Page, test } from '@playwright/test';
const D='01KZDISPUTE000000000000001',O='01KZORDER00000000000000001',G='01KZGROUP00000000000000001',B='01KZBUSIN00000000000000001';

test('admin queue defaults to all assignments',async({page})=>{await admin(page);let assignment:string|null=null;await page.route('**/api/v1/admin/disputes?**',async r=>{assignment=new URL(r.request().url()).searchParams.get('assignment');await r.fulfill({json:{content:[],page:0,size:25,totalElements:0,totalPages:0,sort:'priority,desc'}});});await page.goto('/admin/disputes');await expect(page.getByLabel('Assignment')).toHaveValue('ALL');await expect(page.getByText('0 disputes')).toBeVisible();await expect.poll(()=>assignment).toBe('ALL');});

test('buyer opens an item-not-as-described dispute scoped to one business group',async({page})=>{await buyer(page);let submitted:any=null;await page.route(`**/api/v1/orders/${O}/disputes`,async r=>{submitted=JSON.parse(r.request().postData()||'{}');await r.fulfill({status:201,json:detail({status:'OPEN'})});});await page.goto(`/account/orders/${O}/disputes/new?businessGroupId=${G}`);await page.getByLabel('Reason').selectOption('ITEM_NOT_AS_DESCRIBED');await page.getByLabel('What happened?').fill('The item differs materially from the purchase-time snapshot.');await page.getByRole('button',{name:'Submit dispute'}).click();await expect.poll(()=>submitted?.businessGroupId).toBe(G);expect(submitted.reasonCode).toBe('ITEM_NOT_AS_DESCRIBED');});

test('unknown or unauthorized seller dispute shows a safe unavailable state',async({page})=>{await buyer(page);await page.route(`**/api/v1/businesses/${B}/disputes/${D}`,r=>r.fulfill({status:404,json:{error:{message:'An unexpected error occurred.'}}}));await page.goto(`/seller/businesses/${B}/disputes/${D}`);await expect(page.getByRole('alert')).toContainText('Dispute unavailable or not found.');await expect(page.getByRole('alert')).not.toContainText('An unexpected error occurred.');});

test('admin records a full refund recommendation without calling a refund route',async({page})=>{await admin(page);let refundCalls=0;let resolution:any=null;await page.route('**/*refund*',r=>{refundCalls++;return r.abort();});await page.route(`**/api/v1/admin/disputes/${D}`,r=>r.fulfill({json:detail({status:'READY_FOR_DECISION',canResolve:true})}));await page.route(`**/api/v1/admin/disputes/${D}/resolve`,async r=>{resolution=JSON.parse(r.request().postData()||'{}');await r.fulfill({json:detail({status:'REFUND_RECOMMENDED',final:true,resolution:'REFUND_RECOMMENDED'})});});await page.goto(`/admin/disputes/${D}`);await page.getByLabel('Outcome').selectOption('REFUND_RECOMMENDED');await page.getByLabel('Decision reason').fill('Evidence supports the full transaction remedy.');await expect(page.getByText(/does not issue a refund/i)).toBeVisible();await page.getByRole('button',{name:'Record final decision'}).click();await expect.poll(()=>resolution?.resolutionType).toBe('REFUND_RECOMMENDED');expect(refundCalls).toBe(0);});

test('partial recommendation persists a bounded amount only',async({page})=>{await admin(page);let body:any=null;await page.route(`**/api/v1/admin/disputes/${D}`,r=>r.fulfill({json:detail({status:'READY_FOR_DECISION',canResolve:true})}));await page.route(`**/api/v1/admin/disputes/${D}/resolve`,async r=>{body=JSON.parse(r.request().postData()||'{}');await r.fulfill({json:detail({status:'PARTIAL_REFUND_RECOMMENDED',final:true,resolution:'PARTIAL_REFUND_RECOMMENDED'})});});await page.goto(`/admin/disputes/${D}`);await page.getByLabel('Outcome').selectOption('PARTIAL_REFUND_RECOMMENDED');await page.getByLabel('Decision reason').fill('A limited value adjustment is supported.');await page.getByLabel('Recommended amount').fill('25');await page.getByRole('button',{name:'Record final decision'}).click();await expect.poll(()=>body?.recommendedRefundAmount).toBe(25);});

test('other-admin assignment is read-only',async({page})=>{await admin(page);await page.route(`**/api/v1/admin/disputes/${D}`,r=>r.fulfill({json:detail({status:'UNDER_ADMIN_REVIEW',other:true})}));await page.goto(`/admin/disputes/${D}`);await expect(page.getByText('This dispute is assigned to another administrator.')).toBeVisible();await expect(page.getByRole('button',{name:'Add internal note'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Record final decision'})).toHaveCount(0);});

test('no-action counterfeit decision keeps Trust and Safety separate',async({page})=>{await admin(page);let enforcementCalls=0;await page.route('**/api/v1/**/enforcements**',r=>{enforcementCalls++;return r.abort();});await page.route(`**/api/v1/admin/disputes/${D}`,r=>r.fulfill({json:detail({status:'READY_FOR_DECISION',canResolve:true,reason:'COUNTERFEIT_OR_INAUTHENTIC'})}));await page.route(`**/api/v1/admin/disputes/${D}/resolve`,r=>r.fulfill({json:detail({status:'RESOLVED_NO_ACTION',final:true,resolution:'RESOLVED_NO_ACTION'})}));await page.goto(`/admin/disputes/${D}`);await page.getByLabel('Decision reason').fill('Transaction evidence does not support a remedy.');await page.getByRole('button',{name:'Record final decision'}).click();await expect.poll(()=>enforcementCalls).toBe(0);await expect(page.getByText('Transaction resolution does not create enforcement.')).toBeVisible();});

async function buyer(page:Page){await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{authenticated:true,user:{subject:'buyer',email:'b@x',displayName:'Buyer',roles:['USER']},csrf:{headerName:'X-XSRF-TOKEN',parameterName:'_csrf',token:'playwright-csrf'}}}));await page.route('**/api/v1/users/me',r=>r.fulfill({status:503,json:{error:{message:'Use session fallback.'}}}));}
async function admin(page:Page){await buyer(page);await page.route('**/api/v1/admin/me',r=>r.fulfill({json:{data:{userId:'01KZADMIN00000000000000001',role:'PLATFORM_ADMIN',roles:['PLATFORM_ADMIN'],permissions:['admin.dispute.read','admin.dispute.assign','admin.dispute.investigate','admin.dispute.resolve'],accountState:'ACTIVE'}}}));}
function detail(o:{status:string;canResolve?:boolean;final?:boolean;resolution?:string;other?:boolean;reason?:string}){const caps={canRead:true,canClaim:false,canRelease:false,canInvestigate:false,canAddNote:false,canRequestBuyerInformation:false,canRequestSellerInformation:false,canChangePriority:false,canMarkReadyForDecision:false,canResolve:!!o.canResolve,isAssignedToMe:!!o.canResolve,isAssignedToOther:!!o.other,isFinal:!!o.final,isReadOnly:!!o.final||!!o.other,readOnlyReason:o.other?'This dispute is assigned to another administrator.':o.final?'This dispute has a final decision.':null};return{summary:{disputeId:D,orderId:O,businessGroupId:G,buyerUserId:'01KZBUYER00000000000000001',businessId:B,reasonCode:o.reason||'ITEM_NOT_AS_DESCRIBED',priority:'MEDIUM',status:o.status,assignedAdminId:o.other?'01KZOTHER00000000000000001':'01KZADMIN00000000000000001',disputedAmount:100,currency:'USD',createdAt:'2026-08-19T01:00:00Z',updatedAt:'2026-08-19T01:00:00Z',version:2},openedByType:'BUYER',openedByUserId:'01KZBUYER00000000000000001',description:'The item differs from the purchase-time snapshot.',disputedItems:[{itemId:'01KZITEM000000000000000001',listingId:'01KZLISTIN00000000000000001',titleAtPurchase:'Snapshot camera',skuAtPurchase:'CAM-1',conditionAtPurchase:'NEW',imageReferenceAtPurchase:null,quantity:1,unitPrice:100,lineTotal:100,currency:'USD',currentListing:{available:true,title:'Current camera',status:'ACTIVE',price:105,currency:'USD',version:4},adminPath:'/admin/listings/moderation/01KZLISTIN00000000000000001'}],statements:[],evidence:[],internalNotes:[],timeline:[],resolution:o.resolution?{type:o.resolution,reasonCode:'ADMIN_REVIEW_COMPLETE',reason:'Decision recorded',recommendedRefundAmount:o.resolution.includes('REFUND')?100:null,currency:'USD',returnInstructions:null,returnDeadline:null,resolvedAt:'2026-08-19T02:00:00Z'}:null,currentlyRefundableAmount:100,alreadyRefundedAmount:0,orderStatus:'CONFIRMED',paymentStatus:'SUCCEEDED',inventoryReservationStatus:'COMMITTED',inventoryReleaseStatus:'NOT_REQUIRED',fulfillmentStatus:'DELIVERED',shipment:{source:'LOCAL_DEMO_MANUAL',carrierDisplayName:'Parcel Co',serviceDisplayName:'Ground',trackingNumber:'SAFE-TRACKING',status:'DELIVERED',shippedAt:'2026-08-18T01:00:00Z',deliveredAt:'2026-08-19T00:00:00Z'},cancellationStatus:'NONE',buyerAdminPath:'/admin/users/01KZBUYER00000000000000001',businessAdminPath:`/admin/businesses/${B}`,trustAndSafetyPaths:['/admin/reports','/admin/cases'],capabilities:caps};}
