import { expect, Page, test } from '@playwright/test';

const TICKET='01KZSUPPORT000000000000001';
const USER='01KZBUYER00000000000000001';
const ADMIN='01KZADMIN00000000000000001';
const OTHER='01KZADMIN00000000000000002';
const ORDER='01KZORDER00000000000000001';
const PAYMENT='01KZPAYMENT000000000000001';
const REFUND='01KZREFUND000000000000001';
const DISPUTE='01KZDISPUTE000000000000001';
const REPORT='01KZREPORT0000000000000001';

test('admin dashboard surfaces the unassigned Support queue',async({page})=>{await admin(page);await page.route('**/api/v1/admin/dashboard-summary',route=>route.fulfill({json:{data:{pendingBusinessApplications:0}}}));await page.route('**/api/v1/admin/listings/moderation/summary',route=>route.fulfill({json:{pendingListingReviews:0,assignedToMeListingReviews:0}}));await page.route('**/api/v1/admin/support/tickets?**',async route=>{const url=new URL(route.request().url());expect(url.searchParams.get('assignment')).toBe('UNASSIGNED');expect(url.searchParams.get('size')).toBe('1');await route.fulfill({json:{data:{items:[],page:0,size:1,totalElements:3,totalPages:3,sort:'updatedAt,desc'}}});});await page.goto('/admin');const support=page.getByRole('link',{name:/Support inbox/});await expect(support).toHaveAttribute('href','/admin/support');await expect(support).toContainText('3');await expect(support).toContainText('Unassigned tickets');});

test('requester submits, exchanges messages, and sees safe resolution',async({page})=>{await requester(page);let user=participant('OPEN'),resolved=false;await page.route('**/api/v1/support/tickets',async route=>{expect(JSON.parse(route.request().postData()||'{}').category).toBe('ACCOUNT_HELP');await route.fulfill({status:201,json:{data:user}});});await page.route(`**/api/v1/support/tickets/${TICKET}`,route=>route.fulfill({json:{data:resolved?participant('RESOLVED'):user}}));await page.route(`**/api/v1/support/tickets/${TICKET}/messages`,async route=>{user={...participant('UNDER_REVIEW'),messages:[...participant('OPEN').messages,{messageId:'m2',author:'You',body:'The issue still happens.',createdAt:'2026-08-21T02:10:00Z'}]};await route.fulfill({json:{data:user}});});await page.goto('/support/new');await page.getByLabel('Subject').fill('Cannot update profile');await page.getByLabel('What happened?').fill('My profile changes are not being saved after submission.');await page.getByRole('button',{name:'Submit support request'}).click();await expect(page.getByRole('heading',{name:'Cannot update profile'})).toBeVisible();await page.getByLabel('Your reply').fill('The issue still happens.');await page.getByRole('button',{name:'Send reply'}).click();await expect(page.getByText('The issue still happens.')).toBeVisible();resolved=true;await page.reload();await expect(page.getByRole('heading',{name:'Resolution'})).toBeVisible();await expect(page.getByText('Status explained and issue resolved.')).toBeVisible();await expect(page.getByText(/internal/i)).toHaveCount(0);});

test('order support exposes a validated navigation link and makes no order mutation',async({page})=>{await admin(page);let mutations=0;await page.route('**/api/v1/admin/orders/**',route=>{if(route.request().method()!=='GET')mutations++;return route.abort();});await detailRoute(page,adminDetail({links:[link('ORDER',ORDER,'Order MSB-1001',`/admin/orders/${ORDER}`)],context:{[`ORDER:${ORDER}`]:{status:'CONFIRMED',paymentStatus:'SUCCEEDED'}}}));await page.goto(`/admin/support/${TICKET}`);const owning=page.getByRole('link',{name:'Open owning workflow'});await expect(owning).toHaveAttribute('href',`/admin/orders/${ORDER}`);await expect(page.getByText('Validated read-only context')).toBeVisible();expect(mutations).toBe(0);});

test('refund support stays read-only without finance execution permission',async({page})=>{await admin(page);await detailRoute(page,adminDetail({links:[link('PAYMENT',PAYMENT,'Payment '+PAYMENT,`/admin/payments/${PAYMENT}`),link('REFUND',REFUND,'Refund '+REFUND,`/admin/refunds/${REFUND}`)],context:{[`REFUND:${REFUND}`]:{status:'PROCESSING',reconciliation:'PENDING'}}}));await page.goto(`/admin/support/${TICKET}`);await expect(page.getByText(/does not refund, cancel, suspend, or enforce/i)).toBeVisible();await expect(page.getByRole('button',{name:/issue refund|execute refund/i})).toHaveCount(0);});

test('support explicitly links an existing dispute without executing a refund',async({page})=>{await admin(page);let body:any=null;let refundCalls=0;let current=adminDetail();await detailRoute(page,current);await page.route(`**/api/v1/admin/support/tickets/${TICKET}/escalations`,async route=>{body=JSON.parse(route.request().postData()||'{}');current=adminDetail({escalations:[{escalationId:'e1',destinationType:'DISPUTE',destinationId:DISPUTE,adminPath:`/admin/disputes/${DISPUTE}`,createdByAdminId:ADMIN,reason:'Formal transaction disagreement',createdAt:'2026-08-21T03:00:00Z'}]});await route.fulfill({json:{data:current}});});await page.route('**/*refund*',route=>{refundCalls++;return route.abort();});await page.goto(`/admin/support/${TICKET}`);await page.locator('.escalation select').selectOption('DISPUTE');await page.getByLabel('Existing destination ID').fill(DISPUTE);await page.getByLabel('Handoff reason').fill('Formal transaction disagreement');await page.getByRole('button',{name:'Record handoff'}).click();await expect.poll(()=>body?.destinationType).toBe('DISPUTE');expect(refundCalls).toBe(0);await expect(page.getByText('Formal transaction disagreement')).toBeVisible();});

test('Trust and Safety handoff records traceability without enforcement',async({page})=>{await admin(page);let enforcementCalls=0;let handoff:any=null;await detailRoute(page,adminDetail());await page.route('**/api/v1/**/enforcement**',route=>{enforcementCalls++;return route.abort();});await page.route(`**/api/v1/admin/support/tickets/${TICKET}/escalations`,async route=>{handoff=JSON.parse(route.request().postData()||'{}');await route.fulfill({json:{data:adminDetail({escalations:[{escalationId:'e2',destinationType:'TRUST_AND_SAFETY',destinationId:REPORT,adminPath:`/admin/reports/${REPORT}`,createdByAdminId:ADMIN,reason:'Possible counterfeit behavior',createdAt:'2026-08-21T03:00:00Z'}]})}});});await page.goto(`/admin/support/${TICKET}`);await page.locator('.escalation select').selectOption('TRUST_AND_SAFETY');await page.getByLabel('Existing destination ID').fill(REPORT);await page.getByLabel('Handoff reason').fill('Possible counterfeit behavior');await page.getByRole('button',{name:'Record handoff'}).click();await expect.poll(()=>handoff?.destinationId).toBe(REPORT);expect(enforcementCalls).toBe(0);await expect(page.getByRole('link',{name:'Open destination'})).toHaveAttribute('href',`/admin/reports/${REPORT}`);});

test('two admins respect ownership through release and re-claim',async({page})=>{await admin(page);let current=adminDetail({assignedAdminId:ADMIN,other:true});await page.route(`**/api/v1/admin/support/tickets/${TICKET}`,route=>route.fulfill({json:{data:current}}));await page.route(`**/api/v1/admin/support/tickets/${TICKET}/release`,async route=>{current=adminDetail({assignedAdminId:null,claimable:true});await route.fulfill({json:{data:current}});});await page.route(`**/api/v1/admin/support/tickets/${TICKET}/claim`,async route=>{current=adminDetail({assignedAdminId:OTHER});await route.fulfill({json:{data:current}});});await page.goto(`/admin/support/${TICKET}`);await expect(page.getByText(/assigned to another support admin/i)).toBeVisible();await expect(page.getByRole('button',{name:'Send response'})).toHaveCount(0);current=adminDetail({assignedAdminId:OTHER});await page.reload();await page.getByRole('button',{name:'Release ticket'}).click();await page.getByRole('button',{name:'Claim ticket'}).click();await expect(page.getByRole('button',{name:'Send response'})).toBeVisible();});

async function requester(page:Page){await page.route('**/api/v1/auth/session',route=>route.fulfill({json:{authenticated:true,user:{subject:USER,email:'buyer@msb.local',displayName:'Marketplace Buyer',roles:['USER']},csrf:{headerName:'X-XSRF-TOKEN',parameterName:'_csrf',token:'csrf'}}}));await page.route('**/api/v1/users/me',route=>route.fulfill({status:503,json:{error:{message:'Use session fallback.'}}}));}
async function admin(page:Page){await requester(page);await page.route('**/api/v1/admin/me',route=>route.fulfill({json:{data:{userId:OTHER,role:'SUPPORT_ADMIN',roles:['SUPPORT_ADMIN'],permissions:['admin.dashboard.read','admin.support.read','admin.support.assign','admin.support.respond','admin.support.resolve','admin.support.escalate'],accountState:'ACTIVE'}}}));}
async function detailRoute(page:Page,value:any){await page.route(`**/api/v1/admin/support/tickets/${TICKET}`,route=>route.fulfill({json:{data:value}}));}
function participant(status:string){return{ticketId:TICKET,category:'ACCOUNT_HELP',subject:'Cannot update profile',description:'My profile changes are not being saved after submission.',status,createdAt:'2026-08-21T02:00:00Z',updatedAt:'2026-08-21T02:10:00Z',version:status==='RESOLVED'?4:1,linkedReferences:[],messages:[{messageId:'m1',author:'Support team',body:'Please try the account page again.',createdAt:'2026-08-21T02:05:00Z'}],resolutionCode:status==='RESOLVED'?'ISSUE_RESOLVED':null,resolutionReason:status==='RESOLVED'?'Status explained and issue resolved.':null,resolvedAt:status==='RESOLVED'?'2026-08-21T02:20:00Z':null,history:[]};}
function link(targetType:string,targetId:string,safeLabel:string,adminPath:string){return{targetType,targetId,relationType:'RELATED',safeLabel,adminPath,linkedByType:'ADMIN',linkedBy:ADMIN,linkedAt:'2026-08-21T02:00:00Z'};}
function adminDetail(o:{links?:any[];context?:Record<string,unknown>;escalations?:any[];assignedAdminId?:string|null;other?:boolean;claimable?:boolean}={}){const assigned=o.assignedAdminId===undefined?OTHER:o.assignedAdminId;const mine=assigned===OTHER&&!o.other;const caps={canRead:true,canClaim:!!o.claimable,canRelease:mine,canRespond:mine,canRequestInformation:mine,canAddNote:mine,canChangePriority:mine,canLink:mine,canUnlink:mine,canResolve:mine,canEscalate:mine,isAssignedToMe:mine,isAssignedToOther:!!o.other,isWaitingForUser:false,isFinal:false,isReadOnly:!!o.other,readOnlyReason:o.other?'This ticket is assigned to another support admin.':assigned===null?'Claim this ticket before working on it.':null};return{summary:{ticketId:TICKET,requesterUserId:USER,safeRequesterLabel:'Marketplace Buyer',category:'ORDER_HELP',subject:'Help with my order',priority:'MEDIUM',status:assigned?'UNDER_REVIEW':'OPEN',assignedAdminId:assigned,linkedOrderId:null,createdAt:'2026-08-21T02:00:00Z',updatedAt:'2026-08-21T02:00:00Z',version:2},requester:{userId:USER,safeDisplayName:'Marketplace Buyer',accountState:'ACTIVE',piiAvailable:false,email:null},description:'I need help understanding what happened with this marketplace transaction.',messages:[],internalNotes:[],linkedEntities:o.links||[],escalations:o.escalations||[],linkedContext:o.context||{},timeline:[],resolutionCode:null,resolutionReason:null,resolvedAt:null,availableAdminCapabilities:caps};}
